# Agent configuration file

# Collector configuration section
[grpc_server.grpc]
url = "localhost:8082"
grpc_message_max_size=1000000
[grpc_server.grpc_ui]
enabled = true
url = "localhost:8083"
[postgres]
connstring = "postgres://postgres:example@localhost:5432/sqlsights?sslmode=disable"
[telemetry]
enabled = true
otlp.endpoint = 'localhost:4317'