# Agent configuration file

# Collector configuration section
[grpc_server.grpc]
url = "localhost:8082"
grpc_message_max_size=1000000
[grpc_server.grpc_ui]
enabled = true
url = "localhost:8083"
[elk]
address = "https://localhost:9200"
user = "elastic"
password = "changeme"
[telemetry]
enabled = true
otlp.endpoint = 'localhost:4317'