// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.1
// source: database_monitoring/v1/dbm_api.proto

package dbmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DBMApi_ListSnapshots_FullMethodName = "/database_monitoring.v1.DBMApi/ListSnapshots"
)

// DBMApiClient is the client API for DBMApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DBMApiClient interface {
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
}

type dBMApiClient struct {
	cc grpc.ClientConnInterface
}

func NewDBMApiClient(cc grpc.ClientConnInterface) DBMApiClient {
	return &dBMApiClient{cc}
}

func (c *dBMApiClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, DBMApi_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBMApiServer is the server API for DBMApi service.
// All implementations must embed UnimplementedDBMApiServer
// for forward compatibility.
type DBMApiServer interface {
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	mustEmbedUnimplementedDBMApiServer()
}

// UnimplementedDBMApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBMApiServer struct{}

func (UnimplementedDBMApiServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedDBMApiServer) mustEmbedUnimplementedDBMApiServer() {}
func (UnimplementedDBMApiServer) testEmbeddedByValue()                {}

// UnsafeDBMApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBMApiServer will
// result in compilation errors.
type UnsafeDBMApiServer interface {
	mustEmbedUnimplementedDBMApiServer()
}

func RegisterDBMApiServer(s grpc.ServiceRegistrar, srv DBMApiServer) {
	// If the following call pancis, it indicates UnimplementedDBMApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBMApi_ServiceDesc, srv)
}

func _DBMApi_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBMApiServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBMApi_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBMApiServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DBMApi_ServiceDesc is the grpc.ServiceDesc for DBMApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBMApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "database_monitoring.v1.DBMApi",
	HandlerType: (*DBMApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSnapshots",
			Handler:    _DBMApi_ListSnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database_monitoring/v1/dbm_api.proto",
}
