// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.1
// source: database_monitoring/v1/execution_plan.proto

package dbmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanHandle []byte          `protobuf:"bytes,1,opt,name=plan_handle,json=planHandle,proto3" json:"plan_handle,omitempty"`
	Server     *ServerMetadata `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	XmlPlan    string          `protobuf:"bytes,3,opt,name=xml_plan,json=xmlPlan,proto3" json:"xml_plan,omitempty"`
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionPlan) GetPlanHandle() []byte {
	if x != nil {
		return x.PlanHandle
	}
	return nil
}

func (x *ExecutionPlan) GetServer() *ServerMetadata {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ExecutionPlan) GetXmlPlan() string {
	if x != nil {
		return x.XmlPlan
	}
	return ""
}

var File_database_monitoring_v1_execution_plan_proto protoreflect.FileDescriptor

var file_database_monitoring_v1_execution_plan_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x25, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a,
	0x0d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12,
	0x3e, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x19, 0x0a, 0x08, 0x78, 0x6d, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x78, 0x6d, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x75, 0x69, 0x6c, 0x68, 0x65, 0x72,
	0x6d, 0x65, 0x61, 0x72, 0x70, 0x61, 0x73, 0x73, 0x6f, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76,
	0x31, 0x3b, 0x64, 0x62, 0x6d, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_database_monitoring_v1_execution_plan_proto_rawDescOnce sync.Once
	file_database_monitoring_v1_execution_plan_proto_rawDescData = file_database_monitoring_v1_execution_plan_proto_rawDesc
)

func file_database_monitoring_v1_execution_plan_proto_rawDescGZIP() []byte {
	file_database_monitoring_v1_execution_plan_proto_rawDescOnce.Do(func() {
		file_database_monitoring_v1_execution_plan_proto_rawDescData = protoimpl.X.CompressGZIP(file_database_monitoring_v1_execution_plan_proto_rawDescData)
	})
	return file_database_monitoring_v1_execution_plan_proto_rawDescData
}

var file_database_monitoring_v1_execution_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_database_monitoring_v1_execution_plan_proto_goTypes = []any{
	(*ExecutionPlan)(nil),  // 0: database_monitoring.v1.ExecutionPlan
	(*ServerMetadata)(nil), // 1: database_monitoring.v1.ServerMetadata
}
var file_database_monitoring_v1_execution_plan_proto_depIdxs = []int32{
	1, // 0: database_monitoring.v1.ExecutionPlan.server:type_name -> database_monitoring.v1.ServerMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_database_monitoring_v1_execution_plan_proto_init() }
func file_database_monitoring_v1_execution_plan_proto_init() {
	if File_database_monitoring_v1_execution_plan_proto != nil {
		return
	}
	file_database_monitoring_v1_snapshot_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_database_monitoring_v1_execution_plan_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ExecutionPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_database_monitoring_v1_execution_plan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_monitoring_v1_execution_plan_proto_goTypes,
		DependencyIndexes: file_database_monitoring_v1_execution_plan_proto_depIdxs,
		MessageInfos:      file_database_monitoring_v1_execution_plan_proto_msgTypes,
	}.Build()
	File_database_monitoring_v1_execution_plan_proto = out.File
	file_database_monitoring_v1_execution_plan_proto_rawDesc = nil
	file_database_monitoring_v1_execution_plan_proto_goTypes = nil
	file_database_monitoring_v1_execution_plan_proto_depIdxs = nil
}
