// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: database_monitoring/v1/execution_plan.proto

package dbmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanHandle    string                 `protobuf:"bytes,1,opt,name=plan_handle,json=planHandle,proto3" json:"plan_handle,omitempty"`
	Server        *ServerMetadata        `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	XmlPlan       string                 `protobuf:"bytes,3,opt,name=xml_plan,json=xmlPlan,proto3" json:"xml_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionPlan) GetPlanHandle() string {
	if x != nil {
		return x.PlanHandle
	}
	return ""
}

func (x *ExecutionPlan) GetServer() *ServerMetadata {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ExecutionPlan) GetXmlPlan() string {
	if x != nil {
		return x.XmlPlan
	}
	return ""
}

type ParsedExecutionPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *ExecutionPlan         `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	StatsUsage    []*StatisticsInfo      `protobuf:"bytes,2,rep,name=stats_usage,json=statsUsage,proto3" json:"stats_usage,omitempty"`
	Warnings      []*PlanWarning         `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Nodes         []*PlanNode            `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedExecutionPlan) Reset() {
	*x = ParsedExecutionPlan{}
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedExecutionPlan) ProtoMessage() {}

func (x *ParsedExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedExecutionPlan.ProtoReflect.Descriptor instead.
func (*ParsedExecutionPlan) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedExecutionPlan) GetPlan() *ExecutionPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *ParsedExecutionPlan) GetStatsUsage() []*StatisticsInfo {
	if x != nil {
		return x.StatsUsage
	}
	return nil
}

func (x *ParsedExecutionPlan) GetWarnings() []*PlanWarning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ParsedExecutionPlan) GetNodes() []*PlanNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PlanNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EstimatedRows float64                `protobuf:"fixed64,2,opt,name=estimated_rows,json=estimatedRows,proto3" json:"estimated_rows,omitempty"`
	SubtreeCost   float64                `protobuf:"fixed64,3,opt,name=subtree_cost,json=subtreeCost,proto3" json:"subtree_cost,omitempty"`
	NodeCost      float64                `protobuf:"fixed64,4,opt,name=node_cost,json=nodeCost,proto3" json:"node_cost,omitempty"`
	Header        *PlanNode_Header       `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Nodes         []*PlanNode            `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanNode) Reset() {
	*x = PlanNode{}
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanNode) ProtoMessage() {}

func (x *PlanNode) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanNode.ProtoReflect.Descriptor instead.
func (*PlanNode) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{2}
}

func (x *PlanNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanNode) GetEstimatedRows() float64 {
	if x != nil {
		return x.EstimatedRows
	}
	return 0
}

func (x *PlanNode) GetSubtreeCost() float64 {
	if x != nil {
		return x.SubtreeCost
	}
	return 0
}

func (x *PlanNode) GetNodeCost() float64 {
	if x != nil {
		return x.NodeCost
	}
	return 0
}

func (x *PlanNode) GetHeader() *PlanNode_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PlanNode) GetNodes() []*PlanNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type StatisticsInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastUpdate        string                 `protobuf:"bytes,1,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	ModificationCount int64                  `protobuf:"varint,2,opt,name=modification_count,json=modificationCount,proto3" json:"modification_count,omitempty"`
	SamplingPercent   float64                `protobuf:"fixed64,3,opt,name=sampling_percent,json=samplingPercent,proto3" json:"sampling_percent,omitempty"`
	Statistics        string                 `protobuf:"bytes,4,opt,name=statistics,proto3" json:"statistics,omitempty"`
	Table             string                 `protobuf:"bytes,5,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatisticsInfo) Reset() {
	*x = StatisticsInfo{}
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsInfo) ProtoMessage() {}

func (x *StatisticsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsInfo.ProtoReflect.Descriptor instead.
func (*StatisticsInfo) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{3}
}

func (x *StatisticsInfo) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *StatisticsInfo) GetModificationCount() int64 {
	if x != nil {
		return x.ModificationCount
	}
	return 0
}

func (x *StatisticsInfo) GetSamplingPercent() float64 {
	if x != nil {
		return x.SamplingPercent
	}
	return 0
}

func (x *StatisticsInfo) GetStatistics() string {
	if x != nil {
		return x.Statistics
	}
	return ""
}

func (x *StatisticsInfo) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type PlanWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Warning:
	//
	//	*PlanWarning_Convert
	//	*PlanWarning_MissingIndex
	Warning       isPlanWarning_Warning `protobuf_oneof:"warning"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanWarning) Reset() {
	*x = PlanWarning{}
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanWarning) ProtoMessage() {}

func (x *PlanWarning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanWarning.ProtoReflect.Descriptor instead.
func (*PlanWarning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{4}
}

func (x *PlanWarning) GetWarning() isPlanWarning_Warning {
	if x != nil {
		return x.Warning
	}
	return nil
}

func (x *PlanWarning) GetConvert() *PlanWarning_PlanAffectingConvert {
	if x != nil {
		if x, ok := x.Warning.(*PlanWarning_Convert); ok {
			return x.Convert
		}
	}
	return nil
}

func (x *PlanWarning) GetMissingIndex() *PlanWarning_MissingIndexWarning {
	if x != nil {
		if x, ok := x.Warning.(*PlanWarning_MissingIndex); ok {
			return x.MissingIndex
		}
	}
	return nil
}

type isPlanWarning_Warning interface {
	isPlanWarning_Warning()
}

type PlanWarning_Convert struct {
	Convert *PlanWarning_PlanAffectingConvert `protobuf:"bytes,1,opt,name=convert,proto3,oneof"`
}

type PlanWarning_MissingIndex struct {
	MissingIndex *PlanWarning_MissingIndexWarning `protobuf:"bytes,2,opt,name=missing_index,json=missingIndex,proto3,oneof"`
}

func (*PlanWarning_Convert) isPlanWarning_Warning() {}

func (*PlanWarning_MissingIndex) isPlanWarning_Warning() {}

type PlanNode_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhysicalOp    string                 `protobuf:"bytes,1,opt,name=physical_op,json=physicalOp,proto3" json:"physical_op,omitempty"`
	LogicalOp     string                 `protobuf:"bytes,2,opt,name=logical_op,json=logicalOp,proto3" json:"logical_op,omitempty"`
	EstimateCpu   float64                `protobuf:"fixed64,3,opt,name=estimate_cpu,json=estimateCpu,proto3" json:"estimate_cpu,omitempty"`
	EstimateIo    float64                `protobuf:"fixed64,4,opt,name=estimate_io,json=estimateIo,proto3" json:"estimate_io,omitempty"`
	EstimateRows  float64                `protobuf:"fixed64,5,opt,name=estimate_rows,json=estimateRows,proto3" json:"estimate_rows,omitempty"`
	EstimatedCost float64                `protobuf:"fixed64,6,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	Parallel      string                 `protobuf:"bytes,7,opt,name=parallel,proto3" json:"parallel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanNode_Header) Reset() {
	*x = PlanNode_Header{}
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanNode_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanNode_Header) ProtoMessage() {}

func (x *PlanNode_Header) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanNode_Header.ProtoReflect.Descriptor instead.
func (*PlanNode_Header) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PlanNode_Header) GetPhysicalOp() string {
	if x != nil {
		return x.PhysicalOp
	}
	return ""
}

func (x *PlanNode_Header) GetLogicalOp() string {
	if x != nil {
		return x.LogicalOp
	}
	return ""
}

func (x *PlanNode_Header) GetEstimateCpu() float64 {
	if x != nil {
		return x.EstimateCpu
	}
	return 0
}

func (x *PlanNode_Header) GetEstimateIo() float64 {
	if x != nil {
		return x.EstimateIo
	}
	return 0
}

func (x *PlanNode_Header) GetEstimateRows() float64 {
	if x != nil {
		return x.EstimateRows
	}
	return 0
}

func (x *PlanNode_Header) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *PlanNode_Header) GetParallel() string {
	if x != nil {
		return x.Parallel
	}
	return ""
}

type PlanWarning_PlanAffectingConvert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvertIssue  string                 `protobuf:"bytes,1,opt,name=convert_issue,json=convertIssue,proto3" json:"convert_issue,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanWarning_PlanAffectingConvert) Reset() {
	*x = PlanWarning_PlanAffectingConvert{}
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanWarning_PlanAffectingConvert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanWarning_PlanAffectingConvert) ProtoMessage() {}

func (x *PlanWarning_PlanAffectingConvert) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanWarning_PlanAffectingConvert.ProtoReflect.Descriptor instead.
func (*PlanWarning_PlanAffectingConvert) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PlanWarning_PlanAffectingConvert) GetConvertIssue() string {
	if x != nil {
		return x.ConvertIssue
	}
	return ""
}

func (x *PlanWarning_PlanAffectingConvert) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type PlanWarning_MissingIndexWarning struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Database          string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Schema            string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Table             string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Impact            float64                `protobuf:"fixed64,4,opt,name=impact,proto3" json:"impact,omitempty"`
	EqualityColumns   []string               `protobuf:"bytes,5,rep,name=equality_columns,json=equalityColumns,proto3" json:"equality_columns,omitempty"`
	InequalityColumns []string               `protobuf:"bytes,6,rep,name=inequality_columns,json=inequalityColumns,proto3" json:"inequality_columns,omitempty"`
	IncludeColumns    []string               `protobuf:"bytes,7,rep,name=include_columns,json=includeColumns,proto3" json:"include_columns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanWarning_MissingIndexWarning) Reset() {
	*x = PlanWarning_MissingIndexWarning{}
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanWarning_MissingIndexWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanWarning_MissingIndexWarning) ProtoMessage() {}

func (x *PlanWarning_MissingIndexWarning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_execution_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanWarning_MissingIndexWarning.ProtoReflect.Descriptor instead.
func (*PlanWarning_MissingIndexWarning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_execution_plan_proto_rawDescGZIP(), []int{4, 1}
}

func (x *PlanWarning_MissingIndexWarning) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *PlanWarning_MissingIndexWarning) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *PlanWarning_MissingIndexWarning) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *PlanWarning_MissingIndexWarning) GetImpact() float64 {
	if x != nil {
		return x.Impact
	}
	return 0
}

func (x *PlanWarning_MissingIndexWarning) GetEqualityColumns() []string {
	if x != nil {
		return x.EqualityColumns
	}
	return nil
}

func (x *PlanWarning_MissingIndexWarning) GetInequalityColumns() []string {
	if x != nil {
		return x.InequalityColumns
	}
	return nil
}

func (x *PlanWarning_MissingIndexWarning) GetIncludeColumns() []string {
	if x != nil {
		return x.IncludeColumns
	}
	return nil
}

var File_database_monitoring_v1_execution_plan_proto protoreflect.FileDescriptor

const file_database_monitoring_v1_execution_plan_proto_rawDesc = "" +
	"\n" +
	"+database_monitoring/v1/execution_plan.proto\x12\x16database_monitoring.v1\x1a%database_monitoring/v1/snapshot.proto\"\x8b\x01\n" +
	"\rExecutionPlan\x12\x1f\n" +
	"\vplan_handle\x18\x01 \x01(\tR\n" +
	"planHandle\x12>\n" +
	"\x06server\x18\x02 \x01(\v2&.database_monitoring.v1.ServerMetadataR\x06server\x12\x19\n" +
	"\bxml_plan\x18\x03 \x01(\tR\axmlPlan\"\x92\x02\n" +
	"\x13ParsedExecutionPlan\x129\n" +
	"\x04plan\x18\x01 \x01(\v2%.database_monitoring.v1.ExecutionPlanR\x04plan\x12G\n" +
	"\vstats_usage\x18\x02 \x03(\v2&.database_monitoring.v1.StatisticsInfoR\n" +
	"statsUsage\x12?\n" +
	"\bwarnings\x18\x03 \x03(\v2#.database_monitoring.v1.PlanWarningR\bwarnings\x126\n" +
	"\x05nodes\x18\x04 \x03(\v2 .database_monitoring.v1.PlanNodeR\x05nodes\"\xf5\x03\n" +
	"\bPlanNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eestimated_rows\x18\x02 \x01(\x01R\restimatedRows\x12!\n" +
	"\fsubtree_cost\x18\x03 \x01(\x01R\vsubtreeCost\x12\x1b\n" +
	"\tnode_cost\x18\x04 \x01(\x01R\bnodeCost\x12?\n" +
	"\x06header\x18\x05 \x01(\v2'.database_monitoring.v1.PlanNode.HeaderR\x06header\x126\n" +
	"\x05nodes\x18\a \x03(\v2 .database_monitoring.v1.PlanNodeR\x05nodes\x1a\xf4\x01\n" +
	"\x06Header\x12\x1f\n" +
	"\vphysical_op\x18\x01 \x01(\tR\n" +
	"physicalOp\x12\x1d\n" +
	"\n" +
	"logical_op\x18\x02 \x01(\tR\tlogicalOp\x12!\n" +
	"\festimate_cpu\x18\x03 \x01(\x01R\vestimateCpu\x12\x1f\n" +
	"\vestimate_io\x18\x04 \x01(\x01R\n" +
	"estimateIo\x12#\n" +
	"\restimate_rows\x18\x05 \x01(\x01R\festimateRows\x12%\n" +
	"\x0eestimated_cost\x18\x06 \x01(\x01R\restimatedCost\x12\x1a\n" +
	"\bparallel\x18\a \x01(\tR\bparallel\"\xc1\x01\n" +
	"\x0eStatisticsInfo\x12\x1f\n" +
	"\vlast_update\x18\x01 \x01(\tR\n" +
	"lastUpdate\x12-\n" +
	"\x12modification_count\x18\x02 \x01(\x03R\x11modificationCount\x12)\n" +
	"\x10sampling_percent\x18\x03 \x01(\x01R\x0fsamplingPercent\x12\x1e\n" +
	"\n" +
	"statistics\x18\x04 \x01(\tR\n" +
	"statistics\x12\x14\n" +
	"\x05table\x18\x05 \x01(\tR\x05table\"\xa8\x04\n" +
	"\vPlanWarning\x12T\n" +
	"\aconvert\x18\x01 \x01(\v28.database_monitoring.v1.PlanWarning.PlanAffectingConvertH\x00R\aconvert\x12^\n" +
	"\rmissing_index\x18\x02 \x01(\v27.database_monitoring.v1.PlanWarning.MissingIndexWarningH\x00R\fmissingIndex\x1a[\n" +
	"\x14PlanAffectingConvert\x12#\n" +
	"\rconvert_issue\x18\x01 \x01(\tR\fconvertIssue\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x1a\xfa\x01\n" +
	"\x13MissingIndexWarning\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x16\n" +
	"\x06impact\x18\x04 \x01(\x01R\x06impact\x12)\n" +
	"\x10equality_columns\x18\x05 \x03(\tR\x0fequalityColumns\x12-\n" +
	"\x12inequality_columns\x18\x06 \x03(\tR\x11inequalityColumns\x12'\n" +
	"\x0finclude_columns\x18\a \x03(\tR\x0eincludeColumnsB\t\n" +
	"\awarningBUZSgithub.com/guilhermearpassos/database-monitoring/proto/database_monitoring/v1;dbmv1b\x06proto3"

var (
	file_database_monitoring_v1_execution_plan_proto_rawDescOnce sync.Once
	file_database_monitoring_v1_execution_plan_proto_rawDescData []byte
)

func file_database_monitoring_v1_execution_plan_proto_rawDescGZIP() []byte {
	file_database_monitoring_v1_execution_plan_proto_rawDescOnce.Do(func() {
		file_database_monitoring_v1_execution_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_monitoring_v1_execution_plan_proto_rawDesc), len(file_database_monitoring_v1_execution_plan_proto_rawDesc)))
	})
	return file_database_monitoring_v1_execution_plan_proto_rawDescData
}

var file_database_monitoring_v1_execution_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_database_monitoring_v1_execution_plan_proto_goTypes = []any{
	(*ExecutionPlan)(nil),                    // 0: database_monitoring.v1.ExecutionPlan
	(*ParsedExecutionPlan)(nil),              // 1: database_monitoring.v1.ParsedExecutionPlan
	(*PlanNode)(nil),                         // 2: database_monitoring.v1.PlanNode
	(*StatisticsInfo)(nil),                   // 3: database_monitoring.v1.StatisticsInfo
	(*PlanWarning)(nil),                      // 4: database_monitoring.v1.PlanWarning
	(*PlanNode_Header)(nil),                  // 5: database_monitoring.v1.PlanNode.Header
	(*PlanWarning_PlanAffectingConvert)(nil), // 6: database_monitoring.v1.PlanWarning.PlanAffectingConvert
	(*PlanWarning_MissingIndexWarning)(nil),  // 7: database_monitoring.v1.PlanWarning.MissingIndexWarning
	(*ServerMetadata)(nil),                   // 8: database_monitoring.v1.ServerMetadata
}
var file_database_monitoring_v1_execution_plan_proto_depIdxs = []int32{
	8, // 0: database_monitoring.v1.ExecutionPlan.server:type_name -> database_monitoring.v1.ServerMetadata
	0, // 1: database_monitoring.v1.ParsedExecutionPlan.plan:type_name -> database_monitoring.v1.ExecutionPlan
	3, // 2: database_monitoring.v1.ParsedExecutionPlan.stats_usage:type_name -> database_monitoring.v1.StatisticsInfo
	4, // 3: database_monitoring.v1.ParsedExecutionPlan.warnings:type_name -> database_monitoring.v1.PlanWarning
	2, // 4: database_monitoring.v1.ParsedExecutionPlan.nodes:type_name -> database_monitoring.v1.PlanNode
	5, // 5: database_monitoring.v1.PlanNode.header:type_name -> database_monitoring.v1.PlanNode.Header
	2, // 6: database_monitoring.v1.PlanNode.nodes:type_name -> database_monitoring.v1.PlanNode
	6, // 7: database_monitoring.v1.PlanWarning.convert:type_name -> database_monitoring.v1.PlanWarning.PlanAffectingConvert
	7, // 8: database_monitoring.v1.PlanWarning.missing_index:type_name -> database_monitoring.v1.PlanWarning.MissingIndexWarning
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_database_monitoring_v1_execution_plan_proto_init() }
func file_database_monitoring_v1_execution_plan_proto_init() {
	if File_database_monitoring_v1_execution_plan_proto != nil {
		return
	}
	file_database_monitoring_v1_snapshot_proto_init()
	file_database_monitoring_v1_execution_plan_proto_msgTypes[4].OneofWrappers = []any{
		(*PlanWarning_Convert)(nil),
		(*PlanWarning_MissingIndex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_monitoring_v1_execution_plan_proto_rawDesc), len(file_database_monitoring_v1_execution_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_monitoring_v1_execution_plan_proto_goTypes,
		DependencyIndexes: file_database_monitoring_v1_execution_plan_proto_depIdxs,
		MessageInfos:      file_database_monitoring_v1_execution_plan_proto_msgTypes,
	}.Build()
	File_database_monitoring_v1_execution_plan_proto = out.File
	file_database_monitoring_v1_execution_plan_proto_goTypes = nil
	file_database_monitoring_v1_execution_plan_proto_depIdxs = nil
}
