// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.1
// source: database_monitoring/v1/warning.proto

package dbmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Warning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Server *ServerMetadata `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	// Types that are assignable to Type:
	//
	//	*Warning_Snapshot
	//	*Warning_Plan
	//	*Warning_Query
	Type isWarning_Type `protobuf_oneof:"type"`
}

func (x *Warning) Reset() {
	*x = Warning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{0}
}

func (x *Warning) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Warning) GetServer() *ServerMetadata {
	if x != nil {
		return x.Server
	}
	return nil
}

func (m *Warning) GetType() isWarning_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Warning) GetSnapshot() *SnapshotWarning {
	if x, ok := x.GetType().(*Warning_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *Warning) GetPlan() *ExecutionPlanWarning {
	if x, ok := x.GetType().(*Warning_Plan); ok {
		return x.Plan
	}
	return nil
}

func (x *Warning) GetQuery() *QueryStatWarning {
	if x, ok := x.GetType().(*Warning_Query); ok {
		return x.Query
	}
	return nil
}

type isWarning_Type interface {
	isWarning_Type()
}

type Warning_Snapshot struct {
	Snapshot *SnapshotWarning `protobuf:"bytes,3,opt,name=snapshot,proto3,oneof"`
}

type Warning_Plan struct {
	Plan *ExecutionPlanWarning `protobuf:"bytes,4,opt,name=plan,proto3,oneof"`
}

type Warning_Query struct {
	Query *QueryStatWarning `protobuf:"bytes,5,opt,name=query,proto3,oneof"`
}

func (*Warning_Snapshot) isWarning_Type() {}

func (*Warning_Plan) isWarning_Type() {}

func (*Warning_Query) isWarning_Type() {}

type SnapshotWarning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Warning:
	//
	//	*SnapshotWarning_FrequentLock
	//	*SnapshotWarning_LockingSleepingSession
	Warning isSnapshotWarning_Warning `protobuf_oneof:"warning"`
}

func (x *SnapshotWarning) Reset() {
	*x = SnapshotWarning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotWarning) ProtoMessage() {}

func (x *SnapshotWarning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotWarning.ProtoReflect.Descriptor instead.
func (*SnapshotWarning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{1}
}

func (m *SnapshotWarning) GetWarning() isSnapshotWarning_Warning {
	if m != nil {
		return m.Warning
	}
	return nil
}

func (x *SnapshotWarning) GetFrequentLock() *FrequentLock {
	if x, ok := x.GetWarning().(*SnapshotWarning_FrequentLock); ok {
		return x.FrequentLock
	}
	return nil
}

func (x *SnapshotWarning) GetLockingSleepingSession() *LockingSleepingSession {
	if x, ok := x.GetWarning().(*SnapshotWarning_LockingSleepingSession); ok {
		return x.LockingSleepingSession
	}
	return nil
}

type isSnapshotWarning_Warning interface {
	isSnapshotWarning_Warning()
}

type SnapshotWarning_FrequentLock struct {
	FrequentLock *FrequentLock `protobuf:"bytes,1,opt,name=frequent_lock,json=frequentLock,proto3,oneof"`
}

type SnapshotWarning_LockingSleepingSession struct {
	LockingSleepingSession *LockingSleepingSession `protobuf:"bytes,2,opt,name=locking_sleeping_session,json=lockingSleepingSession,proto3,oneof"`
}

func (*SnapshotWarning_FrequentLock) isSnapshotWarning_Warning() {}

func (*SnapshotWarning_LockingSleepingSession) isSnapshotWarning_Warning() {}

type ExecutionPlanWarning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Warning:
	//
	//	*ExecutionPlanWarning_ImplicitConversion
	//	*ExecutionPlanWarning_MissingIndex
	//	*ExecutionPlanWarning_LargeTableScan
	Warning isExecutionPlanWarning_Warning `protobuf_oneof:"warning"`
}

func (x *ExecutionPlanWarning) Reset() {
	*x = ExecutionPlanWarning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionPlanWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlanWarning) ProtoMessage() {}

func (x *ExecutionPlanWarning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlanWarning.ProtoReflect.Descriptor instead.
func (*ExecutionPlanWarning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{2}
}

func (m *ExecutionPlanWarning) GetWarning() isExecutionPlanWarning_Warning {
	if m != nil {
		return m.Warning
	}
	return nil
}

func (x *ExecutionPlanWarning) GetImplicitConversion() *ImplicitConversion {
	if x, ok := x.GetWarning().(*ExecutionPlanWarning_ImplicitConversion); ok {
		return x.ImplicitConversion
	}
	return nil
}

func (x *ExecutionPlanWarning) GetMissingIndex() *RecommendedIndex {
	if x, ok := x.GetWarning().(*ExecutionPlanWarning_MissingIndex); ok {
		return x.MissingIndex
	}
	return nil
}

func (x *ExecutionPlanWarning) GetLargeTableScan() *LargeTableScan {
	if x, ok := x.GetWarning().(*ExecutionPlanWarning_LargeTableScan); ok {
		return x.LargeTableScan
	}
	return nil
}

type isExecutionPlanWarning_Warning interface {
	isExecutionPlanWarning_Warning()
}

type ExecutionPlanWarning_ImplicitConversion struct {
	ImplicitConversion *ImplicitConversion `protobuf:"bytes,1,opt,name=implicit_conversion,json=implicitConversion,proto3,oneof"`
}

type ExecutionPlanWarning_MissingIndex struct {
	MissingIndex *RecommendedIndex `protobuf:"bytes,2,opt,name=missing_index,json=missingIndex,proto3,oneof"`
}

type ExecutionPlanWarning_LargeTableScan struct {
	LargeTableScan *LargeTableScan `protobuf:"bytes,3,opt,name=large_table_scan,json=largeTableScan,proto3,oneof"`
}

func (*ExecutionPlanWarning_ImplicitConversion) isExecutionPlanWarning_Warning() {}

func (*ExecutionPlanWarning_MissingIndex) isExecutionPlanWarning_Warning() {}

func (*ExecutionPlanWarning_LargeTableScan) isExecutionPlanWarning_Warning() {}

type QueryStatWarning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Warning:
	//
	//	*QueryStatWarning_MemorySpill
	//	*QueryStatWarning_LargeRead
	Warning isQueryStatWarning_Warning `protobuf_oneof:"warning"`
}

func (x *QueryStatWarning) Reset() {
	*x = QueryStatWarning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStatWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatWarning) ProtoMessage() {}

func (x *QueryStatWarning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatWarning.ProtoReflect.Descriptor instead.
func (*QueryStatWarning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{3}
}

func (m *QueryStatWarning) GetWarning() isQueryStatWarning_Warning {
	if m != nil {
		return m.Warning
	}
	return nil
}

func (x *QueryStatWarning) GetMemorySpill() *MemorySpill {
	if x, ok := x.GetWarning().(*QueryStatWarning_MemorySpill); ok {
		return x.MemorySpill
	}
	return nil
}

func (x *QueryStatWarning) GetLargeRead() *LargeRead {
	if x, ok := x.GetWarning().(*QueryStatWarning_LargeRead); ok {
		return x.LargeRead
	}
	return nil
}

type isQueryStatWarning_Warning interface {
	isQueryStatWarning_Warning()
}

type QueryStatWarning_MemorySpill struct {
	MemorySpill *MemorySpill `protobuf:"bytes,1,opt,name=memory_spill,json=memorySpill,proto3,oneof"`
}

type QueryStatWarning_LargeRead struct {
	LargeRead *LargeRead `protobuf:"bytes,2,opt,name=large_read,json=largeRead,proto3,oneof"`
}

func (*QueryStatWarning_MemorySpill) isQueryStatWarning_Warning() {}

func (*QueryStatWarning_LargeRead) isQueryStatWarning_Warning() {}

type FrequentLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceType        string  `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceDescription string  `protobuf:"bytes,2,opt,name=resource_description,json=resourceDescription,proto3" json:"resource_description,omitempty"`
	BlockingQueryHash   string  `protobuf:"bytes,3,opt,name=blocking_query_hash,json=blockingQueryHash,proto3" json:"blocking_query_hash,omitempty"`
	LockCount           int32   `protobuf:"varint,4,opt,name=lock_count,json=lockCount,proto3" json:"lock_count,omitempty"`
	AverageDurationMs   float64 `protobuf:"fixed64,5,opt,name=average_duration_ms,json=averageDurationMs,proto3" json:"average_duration_ms,omitempty"`
	AverageWaiters      float64 `protobuf:"fixed64,6,opt,name=average_waiters,json=averageWaiters,proto3" json:"average_waiters,omitempty"`
}

func (x *FrequentLock) Reset() {
	*x = FrequentLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrequentLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequentLock) ProtoMessage() {}

func (x *FrequentLock) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequentLock.ProtoReflect.Descriptor instead.
func (*FrequentLock) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{4}
}

func (x *FrequentLock) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FrequentLock) GetResourceDescription() string {
	if x != nil {
		return x.ResourceDescription
	}
	return ""
}

func (x *FrequentLock) GetBlockingQueryHash() string {
	if x != nil {
		return x.BlockingQueryHash
	}
	return ""
}

func (x *FrequentLock) GetLockCount() int32 {
	if x != nil {
		return x.LockCount
	}
	return 0
}

func (x *FrequentLock) GetAverageDurationMs() float64 {
	if x != nil {
		return x.AverageDurationMs
	}
	return 0
}

func (x *FrequentLock) GetAverageWaiters() float64 {
	if x != nil {
		return x.AverageWaiters
	}
	return 0
}

type LockingSleepingSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockingQueryHash      string `protobuf:"bytes,1,opt,name=blocking_query_hash,json=blockingQueryHash,proto3" json:"blocking_query_hash,omitempty"`
	MaxBlockedSessionCount int32  `protobuf:"varint,2,opt,name=max_blocked_session_count,json=maxBlockedSessionCount,proto3" json:"max_blocked_session_count,omitempty"`
	MaxBlockingDurationMs  int64  `protobuf:"varint,3,opt,name=max_blocking_duration_ms,json=maxBlockingDurationMs,proto3" json:"max_blocking_duration_ms,omitempty"`
}

func (x *LockingSleepingSession) Reset() {
	*x = LockingSleepingSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockingSleepingSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockingSleepingSession) ProtoMessage() {}

func (x *LockingSleepingSession) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockingSleepingSession.ProtoReflect.Descriptor instead.
func (*LockingSleepingSession) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{5}
}

func (x *LockingSleepingSession) GetBlockingQueryHash() string {
	if x != nil {
		return x.BlockingQueryHash
	}
	return ""
}

func (x *LockingSleepingSession) GetMaxBlockedSessionCount() int32 {
	if x != nil {
		return x.MaxBlockedSessionCount
	}
	return 0
}

func (x *LockingSleepingSession) GetMaxBlockingDurationMs() int64 {
	if x != nil {
		return x.MaxBlockingDurationMs
	}
	return 0
}

type ImplicitConversion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryHash     string `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	QueryPlanHash string `protobuf:"bytes,2,opt,name=query_plan_hash,json=queryPlanHash,proto3" json:"query_plan_hash,omitempty"`
	ColumnName    string `protobuf:"bytes,3,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	FromType      string `protobuf:"bytes,4,opt,name=from_type,json=fromType,proto3" json:"from_type,omitempty"`
	ToType        string `protobuf:"bytes,5,opt,name=to_type,json=toType,proto3" json:"to_type,omitempty"`
	EstimatedRows int64  `protobuf:"varint,6,opt,name=estimated_rows,json=estimatedRows,proto3" json:"estimated_rows,omitempty"`
	TableName     string `protobuf:"bytes,7,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *ImplicitConversion) Reset() {
	*x = ImplicitConversion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImplicitConversion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplicitConversion) ProtoMessage() {}

func (x *ImplicitConversion) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplicitConversion.ProtoReflect.Descriptor instead.
func (*ImplicitConversion) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{6}
}

func (x *ImplicitConversion) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *ImplicitConversion) GetQueryPlanHash() string {
	if x != nil {
		return x.QueryPlanHash
	}
	return ""
}

func (x *ImplicitConversion) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *ImplicitConversion) GetFromType() string {
	if x != nil {
		return x.FromType
	}
	return ""
}

func (x *ImplicitConversion) GetToType() string {
	if x != nil {
		return x.ToType
	}
	return ""
}

func (x *ImplicitConversion) GetEstimatedRows() int64 {
	if x != nil {
		return x.EstimatedRows
	}
	return 0
}

func (x *ImplicitConversion) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type RecommendedIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryHash     string `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	QueryPlanHash string `protobuf:"bytes,2,opt,name=query_plan_hash,json=queryPlanHash,proto3" json:"query_plan_hash,omitempty"`
	Index         string `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *RecommendedIndex) Reset() {
	*x = RecommendedIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendedIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedIndex) ProtoMessage() {}

func (x *RecommendedIndex) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedIndex.ProtoReflect.Descriptor instead.
func (*RecommendedIndex) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{7}
}

func (x *RecommendedIndex) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *RecommendedIndex) GetQueryPlanHash() string {
	if x != nil {
		return x.QueryPlanHash
	}
	return ""
}

func (x *RecommendedIndex) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

type LargeTableScan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryHash     string `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	QueryPlanHash string `protobuf:"bytes,2,opt,name=query_plan_hash,json=queryPlanHash,proto3" json:"query_plan_hash,omitempty"`
}

func (x *LargeTableScan) Reset() {
	*x = LargeTableScan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LargeTableScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeTableScan) ProtoMessage() {}

func (x *LargeTableScan) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeTableScan.ProtoReflect.Descriptor instead.
func (*LargeTableScan) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{8}
}

func (x *LargeTableScan) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *LargeTableScan) GetQueryPlanHash() string {
	if x != nil {
		return x.QueryPlanHash
	}
	return ""
}

type MemorySpill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryHash string `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
}

func (x *MemorySpill) Reset() {
	*x = MemorySpill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemorySpill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySpill) ProtoMessage() {}

func (x *MemorySpill) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySpill.ProtoReflect.Descriptor instead.
func (*MemorySpill) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{9}
}

func (x *MemorySpill) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

type LargeRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryText string `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	QueryHash string `protobuf:"bytes,2,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
}

func (x *LargeRead) Reset() {
	*x = LargeRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_monitoring_v1_warning_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LargeRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeRead) ProtoMessage() {}

func (x *LargeRead) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeRead.ProtoReflect.Descriptor instead.
func (*LargeRead) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{10}
}

func (x *LargeRead) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *LargeRead) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

var File_database_monitoring_v1_warning_proto protoreflect.FileDescriptor

var file_database_monitoring_v1_warning_proto_rawDesc = []byte{
	0x0a, 0x24, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x25,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x02, 0x0a, 0x07, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x3e, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x45, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x08,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x42, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x57, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x12, 0x40, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x57, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x42, 0x06,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x0f, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x4b, 0x0a, 0x0d, 0x66, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x6a, 0x0a, 0x18, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x16, 0x6c, 0x6f, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0xa5,
	0x02, 0x0a, 0x14, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e,
	0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x5d, 0x0a, 0x13, 0x69, 0x6d, 0x70, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d,
	0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x12, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x0d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x52, 0x0a, 0x10, 0x6c, 0x61, 0x72, 0x67, 0x65,
	0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x63, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x72, 0x67, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x6c, 0x61, 0x72,
	0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x77,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0xab, 0x01, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x48, 0x0a, 0x0c, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x70, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x53, 0x70, 0x69, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x53, 0x70, 0x69, 0x6c, 0x6c, 0x12, 0x42, 0x0a, 0x0a, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x72,
	0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x61, 0x64, 0x48, 0x00, 0x52, 0x09,
	0x6c, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x61, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x77, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x22, 0x8e, 0x02, 0x0a, 0x0c, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x14, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a,
	0x13, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a,
	0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13,
	0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x61, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x12, 0x27, 0x0a, 0x0f,
	0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x77, 0x61, 0x69, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x57, 0x61,
	0x69, 0x74, 0x65, 0x72, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x16, 0x4c, 0x6f, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2e, 0x0a, 0x13, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x39, 0x0a, 0x19, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x5f,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x16, 0x6d, 0x61, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x18, 0x6d,
	0x61, 0x78, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x6d,
	0x61, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x73, 0x22, 0xf8, 0x01, 0x0a, 0x12, 0x49, 0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x71, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x73, 0x74,
	0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x6f, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x6e,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x22, 0x57, 0x0a, 0x0e, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63,
	0x61, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x26, 0x0a, 0x0f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x6c, 0x61, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x22, 0x2c, 0x0a, 0x0b, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x53, 0x70, 0x69, 0x6c, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x22, 0x49, 0x0a, 0x09, 0x4c, 0x61, 0x72, 0x67, 0x65,
	0x52, 0x65, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61,
	0x73, 0x68, 0x42, 0x55, 0x5a, 0x53, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x75, 0x69, 0x6c, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x61, 0x72, 0x70, 0x61, 0x73, 0x73,
	0x6f, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2d, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67,
	0x2f, 0x76, 0x31, 0x3b, 0x64, 0x62, 0x6d, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_database_monitoring_v1_warning_proto_rawDescOnce sync.Once
	file_database_monitoring_v1_warning_proto_rawDescData = file_database_monitoring_v1_warning_proto_rawDesc
)

func file_database_monitoring_v1_warning_proto_rawDescGZIP() []byte {
	file_database_monitoring_v1_warning_proto_rawDescOnce.Do(func() {
		file_database_monitoring_v1_warning_proto_rawDescData = protoimpl.X.CompressGZIP(file_database_monitoring_v1_warning_proto_rawDescData)
	})
	return file_database_monitoring_v1_warning_proto_rawDescData
}

var file_database_monitoring_v1_warning_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_database_monitoring_v1_warning_proto_goTypes = []any{
	(*Warning)(nil),                // 0: database_monitoring.v1.Warning
	(*SnapshotWarning)(nil),        // 1: database_monitoring.v1.SnapshotWarning
	(*ExecutionPlanWarning)(nil),   // 2: database_monitoring.v1.ExecutionPlanWarning
	(*QueryStatWarning)(nil),       // 3: database_monitoring.v1.QueryStatWarning
	(*FrequentLock)(nil),           // 4: database_monitoring.v1.FrequentLock
	(*LockingSleepingSession)(nil), // 5: database_monitoring.v1.LockingSleepingSession
	(*ImplicitConversion)(nil),     // 6: database_monitoring.v1.ImplicitConversion
	(*RecommendedIndex)(nil),       // 7: database_monitoring.v1.RecommendedIndex
	(*LargeTableScan)(nil),         // 8: database_monitoring.v1.LargeTableScan
	(*MemorySpill)(nil),            // 9: database_monitoring.v1.MemorySpill
	(*LargeRead)(nil),              // 10: database_monitoring.v1.LargeRead
	(*ServerMetadata)(nil),         // 11: database_monitoring.v1.ServerMetadata
}
var file_database_monitoring_v1_warning_proto_depIdxs = []int32{
	11, // 0: database_monitoring.v1.Warning.server:type_name -> database_monitoring.v1.ServerMetadata
	1,  // 1: database_monitoring.v1.Warning.snapshot:type_name -> database_monitoring.v1.SnapshotWarning
	2,  // 2: database_monitoring.v1.Warning.plan:type_name -> database_monitoring.v1.ExecutionPlanWarning
	3,  // 3: database_monitoring.v1.Warning.query:type_name -> database_monitoring.v1.QueryStatWarning
	4,  // 4: database_monitoring.v1.SnapshotWarning.frequent_lock:type_name -> database_monitoring.v1.FrequentLock
	5,  // 5: database_monitoring.v1.SnapshotWarning.locking_sleeping_session:type_name -> database_monitoring.v1.LockingSleepingSession
	6,  // 6: database_monitoring.v1.ExecutionPlanWarning.implicit_conversion:type_name -> database_monitoring.v1.ImplicitConversion
	7,  // 7: database_monitoring.v1.ExecutionPlanWarning.missing_index:type_name -> database_monitoring.v1.RecommendedIndex
	8,  // 8: database_monitoring.v1.ExecutionPlanWarning.large_table_scan:type_name -> database_monitoring.v1.LargeTableScan
	9,  // 9: database_monitoring.v1.QueryStatWarning.memory_spill:type_name -> database_monitoring.v1.MemorySpill
	10, // 10: database_monitoring.v1.QueryStatWarning.large_read:type_name -> database_monitoring.v1.LargeRead
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_database_monitoring_v1_warning_proto_init() }
func file_database_monitoring_v1_warning_proto_init() {
	if File_database_monitoring_v1_warning_proto != nil {
		return
	}
	file_database_monitoring_v1_snapshot_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_database_monitoring_v1_warning_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Warning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SnapshotWarning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ExecutionPlanWarning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*QueryStatWarning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FrequentLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LockingSleepingSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ImplicitConversion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RecommendedIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LargeTableScan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*MemorySpill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_monitoring_v1_warning_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*LargeRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_database_monitoring_v1_warning_proto_msgTypes[0].OneofWrappers = []any{
		(*Warning_Snapshot)(nil),
		(*Warning_Plan)(nil),
		(*Warning_Query)(nil),
	}
	file_database_monitoring_v1_warning_proto_msgTypes[1].OneofWrappers = []any{
		(*SnapshotWarning_FrequentLock)(nil),
		(*SnapshotWarning_LockingSleepingSession)(nil),
	}
	file_database_monitoring_v1_warning_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecutionPlanWarning_ImplicitConversion)(nil),
		(*ExecutionPlanWarning_MissingIndex)(nil),
		(*ExecutionPlanWarning_LargeTableScan)(nil),
	}
	file_database_monitoring_v1_warning_proto_msgTypes[3].OneofWrappers = []any{
		(*QueryStatWarning_MemorySpill)(nil),
		(*QueryStatWarning_LargeRead)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_database_monitoring_v1_warning_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_monitoring_v1_warning_proto_goTypes,
		DependencyIndexes: file_database_monitoring_v1_warning_proto_depIdxs,
		MessageInfos:      file_database_monitoring_v1_warning_proto_msgTypes,
	}.Build()
	File_database_monitoring_v1_warning_proto = out.File
	file_database_monitoring_v1_warning_proto_rawDesc = nil
	file_database_monitoring_v1_warning_proto_goTypes = nil
	file_database_monitoring_v1_warning_proto_depIdxs = nil
}
