// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: database_monitoring/v1/warning.proto

package dbmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Warning struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Server *ServerMetadata        `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Warning_Snapshot
	//	*Warning_Plan
	//	*Warning_Query
	Type          isWarning_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{0}
}

func (x *Warning) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Warning) GetServer() *ServerMetadata {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Warning) GetType() isWarning_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Warning) GetSnapshot() *SnapshotWarning {
	if x != nil {
		if x, ok := x.Type.(*Warning_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Warning) GetPlan() *ExecutionPlanWarning {
	if x != nil {
		if x, ok := x.Type.(*Warning_Plan); ok {
			return x.Plan
		}
	}
	return nil
}

func (x *Warning) GetQuery() *QueryStatWarning {
	if x != nil {
		if x, ok := x.Type.(*Warning_Query); ok {
			return x.Query
		}
	}
	return nil
}

type isWarning_Type interface {
	isWarning_Type()
}

type Warning_Snapshot struct {
	Snapshot *SnapshotWarning `protobuf:"bytes,3,opt,name=snapshot,proto3,oneof"`
}

type Warning_Plan struct {
	Plan *ExecutionPlanWarning `protobuf:"bytes,4,opt,name=plan,proto3,oneof"`
}

type Warning_Query struct {
	Query *QueryStatWarning `protobuf:"bytes,5,opt,name=query,proto3,oneof"`
}

func (*Warning_Snapshot) isWarning_Type() {}

func (*Warning_Plan) isWarning_Type() {}

func (*Warning_Query) isWarning_Type() {}

type SnapshotWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Warning:
	//
	//	*SnapshotWarning_FrequentLock
	//	*SnapshotWarning_LockingSleepingSession
	Warning       isSnapshotWarning_Warning `protobuf_oneof:"warning"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotWarning) Reset() {
	*x = SnapshotWarning{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotWarning) ProtoMessage() {}

func (x *SnapshotWarning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotWarning.ProtoReflect.Descriptor instead.
func (*SnapshotWarning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotWarning) GetWarning() isSnapshotWarning_Warning {
	if x != nil {
		return x.Warning
	}
	return nil
}

func (x *SnapshotWarning) GetFrequentLock() *FrequentLock {
	if x != nil {
		if x, ok := x.Warning.(*SnapshotWarning_FrequentLock); ok {
			return x.FrequentLock
		}
	}
	return nil
}

func (x *SnapshotWarning) GetLockingSleepingSession() *LockingSleepingSession {
	if x != nil {
		if x, ok := x.Warning.(*SnapshotWarning_LockingSleepingSession); ok {
			return x.LockingSleepingSession
		}
	}
	return nil
}

type isSnapshotWarning_Warning interface {
	isSnapshotWarning_Warning()
}

type SnapshotWarning_FrequentLock struct {
	FrequentLock *FrequentLock `protobuf:"bytes,1,opt,name=frequent_lock,json=frequentLock,proto3,oneof"`
}

type SnapshotWarning_LockingSleepingSession struct {
	LockingSleepingSession *LockingSleepingSession `protobuf:"bytes,2,opt,name=locking_sleeping_session,json=lockingSleepingSession,proto3,oneof"`
}

func (*SnapshotWarning_FrequentLock) isSnapshotWarning_Warning() {}

func (*SnapshotWarning_LockingSleepingSession) isSnapshotWarning_Warning() {}

type ExecutionPlanWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Warning:
	//
	//	*ExecutionPlanWarning_ImplicitConversion
	//	*ExecutionPlanWarning_MissingIndex
	//	*ExecutionPlanWarning_LargeTableScan
	Warning       isExecutionPlanWarning_Warning `protobuf_oneof:"warning"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPlanWarning) Reset() {
	*x = ExecutionPlanWarning{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlanWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlanWarning) ProtoMessage() {}

func (x *ExecutionPlanWarning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlanWarning.ProtoReflect.Descriptor instead.
func (*ExecutionPlanWarning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionPlanWarning) GetWarning() isExecutionPlanWarning_Warning {
	if x != nil {
		return x.Warning
	}
	return nil
}

func (x *ExecutionPlanWarning) GetImplicitConversion() *ImplicitConversion {
	if x != nil {
		if x, ok := x.Warning.(*ExecutionPlanWarning_ImplicitConversion); ok {
			return x.ImplicitConversion
		}
	}
	return nil
}

func (x *ExecutionPlanWarning) GetMissingIndex() *RecommendedIndex {
	if x != nil {
		if x, ok := x.Warning.(*ExecutionPlanWarning_MissingIndex); ok {
			return x.MissingIndex
		}
	}
	return nil
}

func (x *ExecutionPlanWarning) GetLargeTableScan() *LargeTableScan {
	if x != nil {
		if x, ok := x.Warning.(*ExecutionPlanWarning_LargeTableScan); ok {
			return x.LargeTableScan
		}
	}
	return nil
}

type isExecutionPlanWarning_Warning interface {
	isExecutionPlanWarning_Warning()
}

type ExecutionPlanWarning_ImplicitConversion struct {
	ImplicitConversion *ImplicitConversion `protobuf:"bytes,1,opt,name=implicit_conversion,json=implicitConversion,proto3,oneof"`
}

type ExecutionPlanWarning_MissingIndex struct {
	MissingIndex *RecommendedIndex `protobuf:"bytes,2,opt,name=missing_index,json=missingIndex,proto3,oneof"`
}

type ExecutionPlanWarning_LargeTableScan struct {
	LargeTableScan *LargeTableScan `protobuf:"bytes,3,opt,name=large_table_scan,json=largeTableScan,proto3,oneof"`
}

func (*ExecutionPlanWarning_ImplicitConversion) isExecutionPlanWarning_Warning() {}

func (*ExecutionPlanWarning_MissingIndex) isExecutionPlanWarning_Warning() {}

func (*ExecutionPlanWarning_LargeTableScan) isExecutionPlanWarning_Warning() {}

type QueryStatWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Warning:
	//
	//	*QueryStatWarning_MemorySpill
	//	*QueryStatWarning_LargeRead
	Warning       isQueryStatWarning_Warning `protobuf_oneof:"warning"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatWarning) Reset() {
	*x = QueryStatWarning{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatWarning) ProtoMessage() {}

func (x *QueryStatWarning) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatWarning.ProtoReflect.Descriptor instead.
func (*QueryStatWarning) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{3}
}

func (x *QueryStatWarning) GetWarning() isQueryStatWarning_Warning {
	if x != nil {
		return x.Warning
	}
	return nil
}

func (x *QueryStatWarning) GetMemorySpill() *MemorySpill {
	if x != nil {
		if x, ok := x.Warning.(*QueryStatWarning_MemorySpill); ok {
			return x.MemorySpill
		}
	}
	return nil
}

func (x *QueryStatWarning) GetLargeRead() *LargeRead {
	if x != nil {
		if x, ok := x.Warning.(*QueryStatWarning_LargeRead); ok {
			return x.LargeRead
		}
	}
	return nil
}

type isQueryStatWarning_Warning interface {
	isQueryStatWarning_Warning()
}

type QueryStatWarning_MemorySpill struct {
	MemorySpill *MemorySpill `protobuf:"bytes,1,opt,name=memory_spill,json=memorySpill,proto3,oneof"`
}

type QueryStatWarning_LargeRead struct {
	LargeRead *LargeRead `protobuf:"bytes,2,opt,name=large_read,json=largeRead,proto3,oneof"`
}

func (*QueryStatWarning_MemorySpill) isQueryStatWarning_Warning() {}

func (*QueryStatWarning_LargeRead) isQueryStatWarning_Warning() {}

type FrequentLock struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResourceType        string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceDescription string                 `protobuf:"bytes,2,opt,name=resource_description,json=resourceDescription,proto3" json:"resource_description,omitempty"`
	BlockingQueryHash   string                 `protobuf:"bytes,3,opt,name=blocking_query_hash,json=blockingQueryHash,proto3" json:"blocking_query_hash,omitempty"`
	LockCount           int32                  `protobuf:"varint,4,opt,name=lock_count,json=lockCount,proto3" json:"lock_count,omitempty"`
	AverageDurationMs   float64                `protobuf:"fixed64,5,opt,name=average_duration_ms,json=averageDurationMs,proto3" json:"average_duration_ms,omitempty"`
	AverageWaiters      float64                `protobuf:"fixed64,6,opt,name=average_waiters,json=averageWaiters,proto3" json:"average_waiters,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FrequentLock) Reset() {
	*x = FrequentLock{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequentLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequentLock) ProtoMessage() {}

func (x *FrequentLock) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequentLock.ProtoReflect.Descriptor instead.
func (*FrequentLock) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{4}
}

func (x *FrequentLock) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FrequentLock) GetResourceDescription() string {
	if x != nil {
		return x.ResourceDescription
	}
	return ""
}

func (x *FrequentLock) GetBlockingQueryHash() string {
	if x != nil {
		return x.BlockingQueryHash
	}
	return ""
}

func (x *FrequentLock) GetLockCount() int32 {
	if x != nil {
		return x.LockCount
	}
	return 0
}

func (x *FrequentLock) GetAverageDurationMs() float64 {
	if x != nil {
		return x.AverageDurationMs
	}
	return 0
}

func (x *FrequentLock) GetAverageWaiters() float64 {
	if x != nil {
		return x.AverageWaiters
	}
	return 0
}

type LockingSleepingSession struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BlockingQueryHash      string                 `protobuf:"bytes,1,opt,name=blocking_query_hash,json=blockingQueryHash,proto3" json:"blocking_query_hash,omitempty"`
	MaxBlockedSessionCount int32                  `protobuf:"varint,2,opt,name=max_blocked_session_count,json=maxBlockedSessionCount,proto3" json:"max_blocked_session_count,omitempty"`
	MaxBlockingDurationMs  int64                  `protobuf:"varint,3,opt,name=max_blocking_duration_ms,json=maxBlockingDurationMs,proto3" json:"max_blocking_duration_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LockingSleepingSession) Reset() {
	*x = LockingSleepingSession{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockingSleepingSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockingSleepingSession) ProtoMessage() {}

func (x *LockingSleepingSession) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockingSleepingSession.ProtoReflect.Descriptor instead.
func (*LockingSleepingSession) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{5}
}

func (x *LockingSleepingSession) GetBlockingQueryHash() string {
	if x != nil {
		return x.BlockingQueryHash
	}
	return ""
}

func (x *LockingSleepingSession) GetMaxBlockedSessionCount() int32 {
	if x != nil {
		return x.MaxBlockedSessionCount
	}
	return 0
}

func (x *LockingSleepingSession) GetMaxBlockingDurationMs() int64 {
	if x != nil {
		return x.MaxBlockingDurationMs
	}
	return 0
}

type ImplicitConversion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryHash     string                 `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	QueryPlanHash string                 `protobuf:"bytes,2,opt,name=query_plan_hash,json=queryPlanHash,proto3" json:"query_plan_hash,omitempty"`
	ColumnName    string                 `protobuf:"bytes,3,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	FromType      string                 `protobuf:"bytes,4,opt,name=from_type,json=fromType,proto3" json:"from_type,omitempty"`
	ToType        string                 `protobuf:"bytes,5,opt,name=to_type,json=toType,proto3" json:"to_type,omitempty"`
	EstimatedRows int64                  `protobuf:"varint,6,opt,name=estimated_rows,json=estimatedRows,proto3" json:"estimated_rows,omitempty"`
	TableName     string                 `protobuf:"bytes,7,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplicitConversion) Reset() {
	*x = ImplicitConversion{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplicitConversion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplicitConversion) ProtoMessage() {}

func (x *ImplicitConversion) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplicitConversion.ProtoReflect.Descriptor instead.
func (*ImplicitConversion) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{6}
}

func (x *ImplicitConversion) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *ImplicitConversion) GetQueryPlanHash() string {
	if x != nil {
		return x.QueryPlanHash
	}
	return ""
}

func (x *ImplicitConversion) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *ImplicitConversion) GetFromType() string {
	if x != nil {
		return x.FromType
	}
	return ""
}

func (x *ImplicitConversion) GetToType() string {
	if x != nil {
		return x.ToType
	}
	return ""
}

func (x *ImplicitConversion) GetEstimatedRows() int64 {
	if x != nil {
		return x.EstimatedRows
	}
	return 0
}

func (x *ImplicitConversion) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type RecommendedIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryHash     string                 `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	QueryPlanHash string                 `protobuf:"bytes,2,opt,name=query_plan_hash,json=queryPlanHash,proto3" json:"query_plan_hash,omitempty"`
	Index         string                 `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedIndex) Reset() {
	*x = RecommendedIndex{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedIndex) ProtoMessage() {}

func (x *RecommendedIndex) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedIndex.ProtoReflect.Descriptor instead.
func (*RecommendedIndex) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{7}
}

func (x *RecommendedIndex) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *RecommendedIndex) GetQueryPlanHash() string {
	if x != nil {
		return x.QueryPlanHash
	}
	return ""
}

func (x *RecommendedIndex) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

type LargeTableScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryHash     string                 `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	QueryPlanHash string                 `protobuf:"bytes,2,opt,name=query_plan_hash,json=queryPlanHash,proto3" json:"query_plan_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeTableScan) Reset() {
	*x = LargeTableScan{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeTableScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeTableScan) ProtoMessage() {}

func (x *LargeTableScan) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeTableScan.ProtoReflect.Descriptor instead.
func (*LargeTableScan) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{8}
}

func (x *LargeTableScan) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *LargeTableScan) GetQueryPlanHash() string {
	if x != nil {
		return x.QueryPlanHash
	}
	return ""
}

type MemorySpill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryHash     string                 `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemorySpill) Reset() {
	*x = MemorySpill{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySpill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySpill) ProtoMessage() {}

func (x *MemorySpill) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySpill.ProtoReflect.Descriptor instead.
func (*MemorySpill) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{9}
}

func (x *MemorySpill) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

type LargeRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryText     string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	QueryHash     string                 `protobuf:"bytes,2,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeRead) Reset() {
	*x = LargeRead{}
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeRead) ProtoMessage() {}

func (x *LargeRead) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_warning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeRead.ProtoReflect.Descriptor instead.
func (*LargeRead) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_warning_proto_rawDescGZIP(), []int{10}
}

func (x *LargeRead) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *LargeRead) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

var File_database_monitoring_v1_warning_proto protoreflect.FileDescriptor

const file_database_monitoring_v1_warning_proto_rawDesc = "" +
	"\n" +
	"$database_monitoring/v1/warning.proto\x12\x16database_monitoring.v1\x1a%database_monitoring/v1/snapshot.proto\"\xae\x02\n" +
	"\aWarning\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\x06server\x18\x02 \x01(\v2&.database_monitoring.v1.ServerMetadataR\x06server\x12E\n" +
	"\bsnapshot\x18\x03 \x01(\v2'.database_monitoring.v1.SnapshotWarningH\x00R\bsnapshot\x12B\n" +
	"\x04plan\x18\x04 \x01(\v2,.database_monitoring.v1.ExecutionPlanWarningH\x00R\x04plan\x12@\n" +
	"\x05query\x18\x05 \x01(\v2(.database_monitoring.v1.QueryStatWarningH\x00R\x05queryB\x06\n" +
	"\x04type\"\xd5\x01\n" +
	"\x0fSnapshotWarning\x12K\n" +
	"\rfrequent_lock\x18\x01 \x01(\v2$.database_monitoring.v1.FrequentLockH\x00R\ffrequentLock\x12j\n" +
	"\x18locking_sleeping_session\x18\x02 \x01(\v2..database_monitoring.v1.LockingSleepingSessionH\x00R\x16lockingSleepingSessionB\t\n" +
	"\awarning\"\xa5\x02\n" +
	"\x14ExecutionPlanWarning\x12]\n" +
	"\x13implicit_conversion\x18\x01 \x01(\v2*.database_monitoring.v1.ImplicitConversionH\x00R\x12implicitConversion\x12O\n" +
	"\rmissing_index\x18\x02 \x01(\v2(.database_monitoring.v1.RecommendedIndexH\x00R\fmissingIndex\x12R\n" +
	"\x10large_table_scan\x18\x03 \x01(\v2&.database_monitoring.v1.LargeTableScanH\x00R\x0elargeTableScanB\t\n" +
	"\awarning\"\xab\x01\n" +
	"\x10QueryStatWarning\x12H\n" +
	"\fmemory_spill\x18\x01 \x01(\v2#.database_monitoring.v1.MemorySpillH\x00R\vmemorySpill\x12B\n" +
	"\n" +
	"large_read\x18\x02 \x01(\v2!.database_monitoring.v1.LargeReadH\x00R\tlargeReadB\t\n" +
	"\awarning\"\x8e\x02\n" +
	"\fFrequentLock\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x121\n" +
	"\x14resource_description\x18\x02 \x01(\tR\x13resourceDescription\x12.\n" +
	"\x13blocking_query_hash\x18\x03 \x01(\tR\x11blockingQueryHash\x12\x1d\n" +
	"\n" +
	"lock_count\x18\x04 \x01(\x05R\tlockCount\x12.\n" +
	"\x13average_duration_ms\x18\x05 \x01(\x01R\x11averageDurationMs\x12'\n" +
	"\x0faverage_waiters\x18\x06 \x01(\x01R\x0eaverageWaiters\"\xbc\x01\n" +
	"\x16LockingSleepingSession\x12.\n" +
	"\x13blocking_query_hash\x18\x01 \x01(\tR\x11blockingQueryHash\x129\n" +
	"\x19max_blocked_session_count\x18\x02 \x01(\x05R\x16maxBlockedSessionCount\x127\n" +
	"\x18max_blocking_duration_ms\x18\x03 \x01(\x03R\x15maxBlockingDurationMs\"\xf8\x01\n" +
	"\x12ImplicitConversion\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x01 \x01(\tR\tqueryHash\x12&\n" +
	"\x0fquery_plan_hash\x18\x02 \x01(\tR\rqueryPlanHash\x12\x1f\n" +
	"\vcolumn_name\x18\x03 \x01(\tR\n" +
	"columnName\x12\x1b\n" +
	"\tfrom_type\x18\x04 \x01(\tR\bfromType\x12\x17\n" +
	"\ato_type\x18\x05 \x01(\tR\x06toType\x12%\n" +
	"\x0eestimated_rows\x18\x06 \x01(\x03R\restimatedRows\x12\x1d\n" +
	"\n" +
	"table_name\x18\a \x01(\tR\ttableName\"o\n" +
	"\x10RecommendedIndex\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x01 \x01(\tR\tqueryHash\x12&\n" +
	"\x0fquery_plan_hash\x18\x02 \x01(\tR\rqueryPlanHash\x12\x14\n" +
	"\x05index\x18\x03 \x01(\tR\x05index\"W\n" +
	"\x0eLargeTableScan\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x01 \x01(\tR\tqueryHash\x12&\n" +
	"\x0fquery_plan_hash\x18\x02 \x01(\tR\rqueryPlanHash\",\n" +
	"\vMemorySpill\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x01 \x01(\tR\tqueryHash\"I\n" +
	"\tLargeRead\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x02 \x01(\tR\tqueryHashBUZSgithub.com/guilhermearpassos/database-monitoring/proto/database_monitoring/v1;dbmv1b\x06proto3"

var (
	file_database_monitoring_v1_warning_proto_rawDescOnce sync.Once
	file_database_monitoring_v1_warning_proto_rawDescData []byte
)

func file_database_monitoring_v1_warning_proto_rawDescGZIP() []byte {
	file_database_monitoring_v1_warning_proto_rawDescOnce.Do(func() {
		file_database_monitoring_v1_warning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_monitoring_v1_warning_proto_rawDesc), len(file_database_monitoring_v1_warning_proto_rawDesc)))
	})
	return file_database_monitoring_v1_warning_proto_rawDescData
}

var file_database_monitoring_v1_warning_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_database_monitoring_v1_warning_proto_goTypes = []any{
	(*Warning)(nil),                // 0: database_monitoring.v1.Warning
	(*SnapshotWarning)(nil),        // 1: database_monitoring.v1.SnapshotWarning
	(*ExecutionPlanWarning)(nil),   // 2: database_monitoring.v1.ExecutionPlanWarning
	(*QueryStatWarning)(nil),       // 3: database_monitoring.v1.QueryStatWarning
	(*FrequentLock)(nil),           // 4: database_monitoring.v1.FrequentLock
	(*LockingSleepingSession)(nil), // 5: database_monitoring.v1.LockingSleepingSession
	(*ImplicitConversion)(nil),     // 6: database_monitoring.v1.ImplicitConversion
	(*RecommendedIndex)(nil),       // 7: database_monitoring.v1.RecommendedIndex
	(*LargeTableScan)(nil),         // 8: database_monitoring.v1.LargeTableScan
	(*MemorySpill)(nil),            // 9: database_monitoring.v1.MemorySpill
	(*LargeRead)(nil),              // 10: database_monitoring.v1.LargeRead
	(*ServerMetadata)(nil),         // 11: database_monitoring.v1.ServerMetadata
}
var file_database_monitoring_v1_warning_proto_depIdxs = []int32{
	11, // 0: database_monitoring.v1.Warning.server:type_name -> database_monitoring.v1.ServerMetadata
	1,  // 1: database_monitoring.v1.Warning.snapshot:type_name -> database_monitoring.v1.SnapshotWarning
	2,  // 2: database_monitoring.v1.Warning.plan:type_name -> database_monitoring.v1.ExecutionPlanWarning
	3,  // 3: database_monitoring.v1.Warning.query:type_name -> database_monitoring.v1.QueryStatWarning
	4,  // 4: database_monitoring.v1.SnapshotWarning.frequent_lock:type_name -> database_monitoring.v1.FrequentLock
	5,  // 5: database_monitoring.v1.SnapshotWarning.locking_sleeping_session:type_name -> database_monitoring.v1.LockingSleepingSession
	6,  // 6: database_monitoring.v1.ExecutionPlanWarning.implicit_conversion:type_name -> database_monitoring.v1.ImplicitConversion
	7,  // 7: database_monitoring.v1.ExecutionPlanWarning.missing_index:type_name -> database_monitoring.v1.RecommendedIndex
	8,  // 8: database_monitoring.v1.ExecutionPlanWarning.large_table_scan:type_name -> database_monitoring.v1.LargeTableScan
	9,  // 9: database_monitoring.v1.QueryStatWarning.memory_spill:type_name -> database_monitoring.v1.MemorySpill
	10, // 10: database_monitoring.v1.QueryStatWarning.large_read:type_name -> database_monitoring.v1.LargeRead
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_database_monitoring_v1_warning_proto_init() }
func file_database_monitoring_v1_warning_proto_init() {
	if File_database_monitoring_v1_warning_proto != nil {
		return
	}
	file_database_monitoring_v1_snapshot_proto_init()
	file_database_monitoring_v1_warning_proto_msgTypes[0].OneofWrappers = []any{
		(*Warning_Snapshot)(nil),
		(*Warning_Plan)(nil),
		(*Warning_Query)(nil),
	}
	file_database_monitoring_v1_warning_proto_msgTypes[1].OneofWrappers = []any{
		(*SnapshotWarning_FrequentLock)(nil),
		(*SnapshotWarning_LockingSleepingSession)(nil),
	}
	file_database_monitoring_v1_warning_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecutionPlanWarning_ImplicitConversion)(nil),
		(*ExecutionPlanWarning_MissingIndex)(nil),
		(*ExecutionPlanWarning_LargeTableScan)(nil),
	}
	file_database_monitoring_v1_warning_proto_msgTypes[3].OneofWrappers = []any{
		(*QueryStatWarning_MemorySpill)(nil),
		(*QueryStatWarning_LargeRead)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_monitoring_v1_warning_proto_rawDesc), len(file_database_monitoring_v1_warning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_monitoring_v1_warning_proto_goTypes,
		DependencyIndexes: file_database_monitoring_v1_warning_proto_depIdxs,
		MessageInfos:      file_database_monitoring_v1_warning_proto_msgTypes,
	}.Build()
	File_database_monitoring_v1_warning_proto = out.File
	file_database_monitoring_v1_warning_proto_goTypes = nil
	file_database_monitoring_v1_warning_proto_depIdxs = nil
}
