// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: database_monitoring/v1/collector/collector_api.proto

package collectorv1

import (
	v1 "github.com/guilhermearpassos/database-monitoring/proto/database_monitoring/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKnownWarningsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *v1.ServerMetadata     `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnownWarningsRequest) Reset() {
	*x = GetKnownWarningsRequest{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnownWarningsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnownWarningsRequest) ProtoMessage() {}

func (x *GetKnownWarningsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnownWarningsRequest.ProtoReflect.Descriptor instead.
func (*GetKnownWarningsRequest) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetKnownWarningsRequest) GetServer() *v1.ServerMetadata {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *GetKnownWarningsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetKnownWarningsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type GetKnownWarningsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warnings      []*v1.Warning          `protobuf:"bytes,1,rep,name=warnings,proto3" json:"warnings,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnownWarningsResponse) Reset() {
	*x = GetKnownWarningsResponse{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnownWarningsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnownWarningsResponse) ProtoMessage() {}

func (x *GetKnownWarningsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnownWarningsResponse.ProtoReflect.Descriptor instead.
func (*GetKnownWarningsResponse) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetKnownWarningsResponse) GetWarnings() []*v1.Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *GetKnownWarningsResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetKnownWarningsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetKnownWarningsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type IngestWarningsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warnings      []*v1.Warning          `protobuf:"bytes,1,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Server        *v1.ServerMetadata     `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestWarningsRequest) Reset() {
	*x = IngestWarningsRequest{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestWarningsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestWarningsRequest) ProtoMessage() {}

func (x *IngestWarningsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestWarningsRequest.ProtoReflect.Descriptor instead.
func (*IngestWarningsRequest) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{2}
}

func (x *IngestWarningsRequest) GetWarnings() []*v1.Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *IngestWarningsRequest) GetServer() *v1.ServerMetadata {
	if x != nil {
		return x.Server
	}
	return nil
}

type IngestWarningsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestWarningsResponse) Reset() {
	*x = IngestWarningsResponse{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestWarningsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestWarningsResponse) ProtoMessage() {}

func (x *IngestWarningsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestWarningsResponse.ProtoReflect.Descriptor instead.
func (*IngestWarningsResponse) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{3}
}

type GetKnownPlanHandlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *v1.ServerMetadata     `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnownPlanHandlesRequest) Reset() {
	*x = GetKnownPlanHandlesRequest{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnownPlanHandlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnownPlanHandlesRequest) ProtoMessage() {}

func (x *GetKnownPlanHandlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnownPlanHandlesRequest.ProtoReflect.Descriptor instead.
func (*GetKnownPlanHandlesRequest) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetKnownPlanHandlesRequest) GetServer() *v1.ServerMetadata {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *GetKnownPlanHandlesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetKnownPlanHandlesRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type GetKnownPlanHandlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handles       []string               `protobuf:"bytes,1,rep,name=handles,proto3" json:"handles,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnownPlanHandlesResponse) Reset() {
	*x = GetKnownPlanHandlesResponse{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnownPlanHandlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnownPlanHandlesResponse) ProtoMessage() {}

func (x *GetKnownPlanHandlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnownPlanHandlesResponse.ProtoReflect.Descriptor instead.
func (*GetKnownPlanHandlesResponse) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetKnownPlanHandlesResponse) GetHandles() []string {
	if x != nil {
		return x.Handles
	}
	return nil
}

func (x *GetKnownPlanHandlesResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetKnownPlanHandlesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetKnownPlanHandlesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type IngestExecutionPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*v1.ExecutionPlan    `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestExecutionPlansRequest) Reset() {
	*x = IngestExecutionPlansRequest{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestExecutionPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestExecutionPlansRequest) ProtoMessage() {}

func (x *IngestExecutionPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestExecutionPlansRequest.ProtoReflect.Descriptor instead.
func (*IngestExecutionPlansRequest) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{6}
}

func (x *IngestExecutionPlansRequest) GetPlans() []*v1.ExecutionPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type IngestExecutionPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestExecutionPlansResponse) Reset() {
	*x = IngestExecutionPlansResponse{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestExecutionPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestExecutionPlansResponse) ProtoMessage() {}

func (x *IngestExecutionPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestExecutionPlansResponse.ProtoReflect.Descriptor instead.
func (*IngestExecutionPlansResponse) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{7}
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetHost    string                 `protobuf:"bytes,1,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetType    string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterAgentRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *RegisterAgentRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *RegisterAgentRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterAgentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{9}
}

type IngestMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestMetricsResponse) Reset() {
	*x = IngestMetricsResponse{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestMetricsResponse) ProtoMessage() {}

func (x *IngestMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestMetricsResponse.ProtoReflect.Descriptor instead.
func (*IngestMetricsResponse) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{10}
}

func (x *IngestMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IngestSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *v1.DBSnapshot         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSnapshotRequest) Reset() {
	*x = IngestSnapshotRequest{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSnapshotRequest) ProtoMessage() {}

func (x *IngestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*IngestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{11}
}

func (x *IngestSnapshotRequest) GetSnapshot() *v1.DBSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type IngestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSnapshotResponse) Reset() {
	*x = IngestSnapshotResponse{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSnapshotResponse) ProtoMessage() {}

func (x *IngestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*IngestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{12}
}

type IngestSnapshotSamplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Samples       []*v1.QuerySample      `protobuf:"bytes,5,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSnapshotSamplesRequest) Reset() {
	*x = IngestSnapshotSamplesRequest{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSnapshotSamplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSnapshotSamplesRequest) ProtoMessage() {}

func (x *IngestSnapshotSamplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSnapshotSamplesRequest.ProtoReflect.Descriptor instead.
func (*IngestSnapshotSamplesRequest) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{13}
}

func (x *IngestSnapshotSamplesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestSnapshotSamplesRequest) GetSamples() []*v1.QuerySample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type IngestSnapshotSamplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSnapshotSamplesResponse) Reset() {
	*x = IngestSnapshotSamplesResponse{}
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSnapshotSamplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSnapshotSamplesResponse) ProtoMessage() {}

func (x *IngestSnapshotSamplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_collector_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSnapshotSamplesResponse.ProtoReflect.Descriptor instead.
func (*IngestSnapshotSamplesResponse) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP(), []int{14}
}

var File_database_monitoring_v1_collector_collector_api_proto protoreflect.FileDescriptor

const file_database_monitoring_v1_collector_collector_api_proto_rawDesc = "" +
	"\n" +
	"4database_monitoring/v1/collector/collector_api.proto\x12\x16database_monitoring.v1\x1a.database_monitoring/v1/collector/metrics.proto\x1a%database_monitoring/v1/snapshot.proto\x1a+database_monitoring/v1/execution_plan.proto\x1a#database_monitoring/v1/sample.proto\x1a$database_monitoring/v1/warning.proto\"\x97\x01\n" +
	"\x17GetKnownWarningsRequest\x12>\n" +
	"\x06server\x18\x01 \x01(\v2&.database_monitoring.v1.ServerMetadataR\x06server\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\"\xb6\x01\n" +
	"\x18GetKnownWarningsResponse\x12;\n" +
	"\bwarnings\x18\x01 \x03(\v2\x1f.database_monitoring.v1.WarningR\bwarnings\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\x94\x01\n" +
	"\x15IngestWarningsRequest\x12;\n" +
	"\bwarnings\x18\x01 \x03(\v2\x1f.database_monitoring.v1.WarningR\bwarnings\x12>\n" +
	"\x06server\x18\x02 \x01(\v2&.database_monitoring.v1.ServerMetadataR\x06server\"\x18\n" +
	"\x16IngestWarningsResponse\"\x9a\x01\n" +
	"\x1aGetKnownPlanHandlesRequest\x12>\n" +
	"\x06server\x18\x01 \x01(\v2&.database_monitoring.v1.ServerMetadataR\x06server\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\"\x96\x01\n" +
	"\x1bGetKnownPlanHandlesResponse\x12\x18\n" +
	"\ahandles\x18\x01 \x03(\tR\ahandles\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"Z\n" +
	"\x1bIngestExecutionPlansRequest\x12;\n" +
	"\x05plans\x18\x01 \x03(\v2%.database_monitoring.v1.ExecutionPlanR\x05plans\"\x1e\n" +
	"\x1cIngestExecutionPlansResponse\"\x91\x01\n" +
	"\x14RegisterAgentRequest\x12\x1f\n" +
	"\vtarget_host\x18\x01 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x17\n" +
	"\x15RegisterAgentResponse\"K\n" +
	"\x15IngestMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x15IngestSnapshotRequest\x12>\n" +
	"\bsnapshot\x18\x01 \x01(\v2\".database_monitoring.v1.DBSnapshotR\bsnapshot\"\x18\n" +
	"\x16IngestSnapshotResponse\"m\n" +
	"\x1cIngestSnapshotSamplesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\asamples\x18\x05 \x03(\v2#.database_monitoring.v1.QuerySampleR\asamples\"\x1f\n" +
	"\x1dIngestSnapshotSamplesResponse2\xcd\a\n" +
	"\x10IngestionService\x12l\n" +
	"\rRegisterAgent\x12,.database_monitoring.v1.RegisterAgentRequest\x1a-.database_monitoring.v1.RegisterAgentResponse\x12g\n" +
	"\rIngestMetrics\x12'.database_monitoring.v1.DatabaseMetrics\x1a-.database_monitoring.v1.IngestMetricsResponse\x12o\n" +
	"\x0eIngestSnapshot\x12-.database_monitoring.v1.IngestSnapshotRequest\x1a..database_monitoring.v1.IngestSnapshotResponse\x12\x84\x01\n" +
	"\x15IngestSnapshotSamples\x124.database_monitoring.v1.IngestSnapshotSamplesRequest\x1a5.database_monitoring.v1.IngestSnapshotSamplesResponse\x12\x81\x01\n" +
	"\x14IngestExecutionPlans\x123.database_monitoring.v1.IngestExecutionPlansRequest\x1a4.database_monitoring.v1.IngestExecutionPlansResponse\x12~\n" +
	"\x13GetKnownPlanHandles\x122.database_monitoring.v1.GetKnownPlanHandlesRequest\x1a3.database_monitoring.v1.GetKnownPlanHandlesResponse\x12o\n" +
	"\x0eIngestWarnings\x12-.database_monitoring.v1.IngestWarningsRequest\x1a..database_monitoring.v1.IngestWarningsResponse\x12u\n" +
	"\x10GetKnownWarnings\x12/.database_monitoring.v1.GetKnownWarningsRequest\x1a0.database_monitoring.v1.GetKnownWarningsResponseBeZcgithub.com/guilhermearpassos/database-monitoring/proto/database_monitoring/v1/collector;collectorv1b\x06proto3"

var (
	file_database_monitoring_v1_collector_collector_api_proto_rawDescOnce sync.Once
	file_database_monitoring_v1_collector_collector_api_proto_rawDescData []byte
)

func file_database_monitoring_v1_collector_collector_api_proto_rawDescGZIP() []byte {
	file_database_monitoring_v1_collector_collector_api_proto_rawDescOnce.Do(func() {
		file_database_monitoring_v1_collector_collector_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_monitoring_v1_collector_collector_api_proto_rawDesc), len(file_database_monitoring_v1_collector_collector_api_proto_rawDesc)))
	})
	return file_database_monitoring_v1_collector_collector_api_proto_rawDescData
}

var file_database_monitoring_v1_collector_collector_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_database_monitoring_v1_collector_collector_api_proto_goTypes = []any{
	(*GetKnownWarningsRequest)(nil),       // 0: database_monitoring.v1.GetKnownWarningsRequest
	(*GetKnownWarningsResponse)(nil),      // 1: database_monitoring.v1.GetKnownWarningsResponse
	(*IngestWarningsRequest)(nil),         // 2: database_monitoring.v1.IngestWarningsRequest
	(*IngestWarningsResponse)(nil),        // 3: database_monitoring.v1.IngestWarningsResponse
	(*GetKnownPlanHandlesRequest)(nil),    // 4: database_monitoring.v1.GetKnownPlanHandlesRequest
	(*GetKnownPlanHandlesResponse)(nil),   // 5: database_monitoring.v1.GetKnownPlanHandlesResponse
	(*IngestExecutionPlansRequest)(nil),   // 6: database_monitoring.v1.IngestExecutionPlansRequest
	(*IngestExecutionPlansResponse)(nil),  // 7: database_monitoring.v1.IngestExecutionPlansResponse
	(*RegisterAgentRequest)(nil),          // 8: database_monitoring.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),         // 9: database_monitoring.v1.RegisterAgentResponse
	(*IngestMetricsResponse)(nil),         // 10: database_monitoring.v1.IngestMetricsResponse
	(*IngestSnapshotRequest)(nil),         // 11: database_monitoring.v1.IngestSnapshotRequest
	(*IngestSnapshotResponse)(nil),        // 12: database_monitoring.v1.IngestSnapshotResponse
	(*IngestSnapshotSamplesRequest)(nil),  // 13: database_monitoring.v1.IngestSnapshotSamplesRequest
	(*IngestSnapshotSamplesResponse)(nil), // 14: database_monitoring.v1.IngestSnapshotSamplesResponse
	(*v1.ServerMetadata)(nil),             // 15: database_monitoring.v1.ServerMetadata
	(*v1.Warning)(nil),                    // 16: database_monitoring.v1.Warning
	(*v1.ExecutionPlan)(nil),              // 17: database_monitoring.v1.ExecutionPlan
	(*v1.DBSnapshot)(nil),                 // 18: database_monitoring.v1.DBSnapshot
	(*v1.QuerySample)(nil),                // 19: database_monitoring.v1.QuerySample
	(*DatabaseMetrics)(nil),               // 20: database_monitoring.v1.DatabaseMetrics
}
var file_database_monitoring_v1_collector_collector_api_proto_depIdxs = []int32{
	15, // 0: database_monitoring.v1.GetKnownWarningsRequest.server:type_name -> database_monitoring.v1.ServerMetadata
	16, // 1: database_monitoring.v1.GetKnownWarningsResponse.warnings:type_name -> database_monitoring.v1.Warning
	16, // 2: database_monitoring.v1.IngestWarningsRequest.warnings:type_name -> database_monitoring.v1.Warning
	15, // 3: database_monitoring.v1.IngestWarningsRequest.server:type_name -> database_monitoring.v1.ServerMetadata
	15, // 4: database_monitoring.v1.GetKnownPlanHandlesRequest.server:type_name -> database_monitoring.v1.ServerMetadata
	17, // 5: database_monitoring.v1.IngestExecutionPlansRequest.plans:type_name -> database_monitoring.v1.ExecutionPlan
	18, // 6: database_monitoring.v1.IngestSnapshotRequest.snapshot:type_name -> database_monitoring.v1.DBSnapshot
	19, // 7: database_monitoring.v1.IngestSnapshotSamplesRequest.samples:type_name -> database_monitoring.v1.QuerySample
	8,  // 8: database_monitoring.v1.IngestionService.RegisterAgent:input_type -> database_monitoring.v1.RegisterAgentRequest
	20, // 9: database_monitoring.v1.IngestionService.IngestMetrics:input_type -> database_monitoring.v1.DatabaseMetrics
	11, // 10: database_monitoring.v1.IngestionService.IngestSnapshot:input_type -> database_monitoring.v1.IngestSnapshotRequest
	13, // 11: database_monitoring.v1.IngestionService.IngestSnapshotSamples:input_type -> database_monitoring.v1.IngestSnapshotSamplesRequest
	6,  // 12: database_monitoring.v1.IngestionService.IngestExecutionPlans:input_type -> database_monitoring.v1.IngestExecutionPlansRequest
	4,  // 13: database_monitoring.v1.IngestionService.GetKnownPlanHandles:input_type -> database_monitoring.v1.GetKnownPlanHandlesRequest
	2,  // 14: database_monitoring.v1.IngestionService.IngestWarnings:input_type -> database_monitoring.v1.IngestWarningsRequest
	0,  // 15: database_monitoring.v1.IngestionService.GetKnownWarnings:input_type -> database_monitoring.v1.GetKnownWarningsRequest
	9,  // 16: database_monitoring.v1.IngestionService.RegisterAgent:output_type -> database_monitoring.v1.RegisterAgentResponse
	10, // 17: database_monitoring.v1.IngestionService.IngestMetrics:output_type -> database_monitoring.v1.IngestMetricsResponse
	12, // 18: database_monitoring.v1.IngestionService.IngestSnapshot:output_type -> database_monitoring.v1.IngestSnapshotResponse
	14, // 19: database_monitoring.v1.IngestionService.IngestSnapshotSamples:output_type -> database_monitoring.v1.IngestSnapshotSamplesResponse
	7,  // 20: database_monitoring.v1.IngestionService.IngestExecutionPlans:output_type -> database_monitoring.v1.IngestExecutionPlansResponse
	5,  // 21: database_monitoring.v1.IngestionService.GetKnownPlanHandles:output_type -> database_monitoring.v1.GetKnownPlanHandlesResponse
	3,  // 22: database_monitoring.v1.IngestionService.IngestWarnings:output_type -> database_monitoring.v1.IngestWarningsResponse
	1,  // 23: database_monitoring.v1.IngestionService.GetKnownWarnings:output_type -> database_monitoring.v1.GetKnownWarningsResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_database_monitoring_v1_collector_collector_api_proto_init() }
func file_database_monitoring_v1_collector_collector_api_proto_init() {
	if File_database_monitoring_v1_collector_collector_api_proto != nil {
		return
	}
	file_database_monitoring_v1_collector_metrics_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_monitoring_v1_collector_collector_api_proto_rawDesc), len(file_database_monitoring_v1_collector_collector_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_monitoring_v1_collector_collector_api_proto_goTypes,
		DependencyIndexes: file_database_monitoring_v1_collector_collector_api_proto_depIdxs,
		MessageInfos:      file_database_monitoring_v1_collector_collector_api_proto_msgTypes,
	}.Build()
	File_database_monitoring_v1_collector_collector_api_proto = out.File
	file_database_monitoring_v1_collector_collector_api_proto_goTypes = nil
	file_database_monitoring_v1_collector_collector_api_proto_depIdxs = nil
}
