// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: database_monitoring/v1/collector/metrics.proto

package collectorv1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	v1 "github.com/guilhermearpassos/database-monitoring/proto/database_monitoring/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseMetrics struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Server    *v1.ServerMetadata     `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Timestamp *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Metrics:
	//
	//	*DatabaseMetrics_QueryMetrics
	//	*DatabaseMetrics_SystemMetrics
	Metrics       isDatabaseMetrics_Metrics `protobuf_oneof:"metrics"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseMetrics) Reset() {
	*x = DatabaseMetrics{}
	mi := &file_database_monitoring_v1_collector_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseMetrics) ProtoMessage() {}

func (x *DatabaseMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseMetrics.ProtoReflect.Descriptor instead.
func (*DatabaseMetrics) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseMetrics) GetServer() *v1.ServerMetadata {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *DatabaseMetrics) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DatabaseMetrics) GetMetrics() isDatabaseMetrics_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *DatabaseMetrics) GetQueryMetrics() *DatabaseMetrics_QueryMetricSample {
	if x != nil {
		if x, ok := x.Metrics.(*DatabaseMetrics_QueryMetrics); ok {
			return x.QueryMetrics
		}
	}
	return nil
}

func (x *DatabaseMetrics) GetSystemMetrics() *SystemMetrics {
	if x != nil {
		if x, ok := x.Metrics.(*DatabaseMetrics_SystemMetrics); ok {
			return x.SystemMetrics
		}
	}
	return nil
}

type isDatabaseMetrics_Metrics interface {
	isDatabaseMetrics_Metrics()
}

type DatabaseMetrics_QueryMetrics struct {
	QueryMetrics *DatabaseMetrics_QueryMetricSample `protobuf:"bytes,3,opt,name=query_metrics,json=queryMetrics,proto3,oneof"`
}

type DatabaseMetrics_SystemMetrics struct {
	SystemMetrics *SystemMetrics `protobuf:"bytes,4,opt,name=system_metrics,json=systemMetrics,proto3,oneof"`
}

func (*DatabaseMetrics_QueryMetrics) isDatabaseMetrics_Metrics() {}

func (*DatabaseMetrics_SystemMetrics) isDatabaseMetrics_Metrics() {}

type SystemMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage          float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage       float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	DiskIoRate        float64                `protobuf:"fixed64,4,opt,name=disk_io_rate,json=diskIoRate,proto3" json:"disk_io_rate,omitempty"`
	NetworkIoRate     float64                `protobuf:"fixed64,5,opt,name=network_io_rate,json=networkIoRate,proto3" json:"network_io_rate,omitempty"`
	Counters          []*PerformanceCounters `protobuf:"bytes,6,rep,name=counters,proto3" json:"counters,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_database_monitoring_v1_collector_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *SystemMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemMetrics) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *SystemMetrics) GetDiskIoRate() float64 {
	if x != nil {
		return x.DiskIoRate
	}
	return 0
}

func (x *SystemMetrics) GetNetworkIoRate() float64 {
	if x != nil {
		return x.NetworkIoRate
	}
	return 0
}

func (x *SystemMetrics) GetCounters() []*PerformanceCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

type PerformanceCounters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CounterName   string                 `protobuf:"bytes,1,opt,name=counter_name,json=counterName,proto3" json:"counter_name,omitempty"`
	CounterValue  int64                  `protobuf:"varint,2,opt,name=counter_value,json=counterValue,proto3" json:"counter_value,omitempty"`
	CounterRate   float64                `protobuf:"fixed64,3,opt,name=counter_rate,json=counterRate,proto3" json:"counter_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceCounters) Reset() {
	*x = PerformanceCounters{}
	mi := &file_database_monitoring_v1_collector_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceCounters) ProtoMessage() {}

func (x *PerformanceCounters) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceCounters.ProtoReflect.Descriptor instead.
func (*PerformanceCounters) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *PerformanceCounters) GetCounterName() string {
	if x != nil {
		return x.CounterName
	}
	return ""
}

func (x *PerformanceCounters) GetCounterValue() int64 {
	if x != nil {
		return x.CounterValue
	}
	return 0
}

func (x *PerformanceCounters) GetCounterRate() float64 {
	if x != nil {
		return x.CounterRate
	}
	return 0
}

type DatabaseMetrics_QueryMetricSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryMetrics  []*v1.QueryMetric      `protobuf:"bytes,1,rep,name=query_metrics,json=queryMetrics,proto3" json:"query_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseMetrics_QueryMetricSample) Reset() {
	*x = DatabaseMetrics_QueryMetricSample{}
	mi := &file_database_monitoring_v1_collector_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseMetrics_QueryMetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseMetrics_QueryMetricSample) ProtoMessage() {}

func (x *DatabaseMetrics_QueryMetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_database_monitoring_v1_collector_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseMetrics_QueryMetricSample.ProtoReflect.Descriptor instead.
func (*DatabaseMetrics_QueryMetricSample) Descriptor() ([]byte, []int) {
	return file_database_monitoring_v1_collector_metrics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DatabaseMetrics_QueryMetricSample) GetQueryMetrics() []*v1.QueryMetric {
	if x != nil {
		return x.QueryMetrics
	}
	return nil
}

var File_database_monitoring_v1_collector_metrics_proto protoreflect.FileDescriptor

const file_database_monitoring_v1_collector_metrics_proto_rawDesc = "" +
	"\n" +
	".database_monitoring/v1/collector/metrics.proto\x12\x16database_monitoring.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#database_monitoring/v1/sample.proto\x1a%database_monitoring/v1/snapshot.proto\"\xa7\x03\n" +
	"\x0fDatabaseMetrics\x12>\n" +
	"\x06server\x18\x01 \x01(\v2&.database_monitoring.v1.ServerMetadataR\x06server\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12`\n" +
	"\rquery_metrics\x18\x03 \x01(\v29.database_monitoring.v1.DatabaseMetrics.QueryMetricSampleH\x00R\fqueryMetrics\x12N\n" +
	"\x0esystem_metrics\x18\x04 \x01(\v2%.database_monitoring.v1.SystemMetricsH\x00R\rsystemMetrics\x1a]\n" +
	"\x11QueryMetricSample\x12H\n" +
	"\rquery_metrics\x18\x01 \x03(\v2#.database_monitoring.v1.QueryMetricR\fqueryMetricsB\t\n" +
	"\ametrics\"\x91\x02\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x03R\x11activeConnections\x12 \n" +
	"\fdisk_io_rate\x18\x04 \x01(\x01R\n" +
	"diskIoRate\x12&\n" +
	"\x0fnetwork_io_rate\x18\x05 \x01(\x01R\rnetworkIoRate\x12G\n" +
	"\bcounters\x18\x06 \x03(\v2+.database_monitoring.v1.PerformanceCountersR\bcounters\"\x80\x01\n" +
	"\x13PerformanceCounters\x12!\n" +
	"\fcounter_name\x18\x01 \x01(\tR\vcounterName\x12#\n" +
	"\rcounter_value\x18\x02 \x01(\x03R\fcounterValue\x12!\n" +
	"\fcounter_rate\x18\x03 \x01(\x01R\vcounterRateBeZcgithub.com/guilhermearpassos/database-monitoring/proto/database_monitoring/v1/collector;collectorv1b\x06proto3"

var (
	file_database_monitoring_v1_collector_metrics_proto_rawDescOnce sync.Once
	file_database_monitoring_v1_collector_metrics_proto_rawDescData []byte
)

func file_database_monitoring_v1_collector_metrics_proto_rawDescGZIP() []byte {
	file_database_monitoring_v1_collector_metrics_proto_rawDescOnce.Do(func() {
		file_database_monitoring_v1_collector_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_monitoring_v1_collector_metrics_proto_rawDesc), len(file_database_monitoring_v1_collector_metrics_proto_rawDesc)))
	})
	return file_database_monitoring_v1_collector_metrics_proto_rawDescData
}

var file_database_monitoring_v1_collector_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_database_monitoring_v1_collector_metrics_proto_goTypes = []any{
	(*DatabaseMetrics)(nil),                   // 0: database_monitoring.v1.DatabaseMetrics
	(*SystemMetrics)(nil),                     // 1: database_monitoring.v1.SystemMetrics
	(*PerformanceCounters)(nil),               // 2: database_monitoring.v1.PerformanceCounters
	(*DatabaseMetrics_QueryMetricSample)(nil), // 3: database_monitoring.v1.DatabaseMetrics.QueryMetricSample
	(*v1.ServerMetadata)(nil),                 // 4: database_monitoring.v1.ServerMetadata
	(*timestamp.Timestamp)(nil),               // 5: google.protobuf.Timestamp
	(*v1.QueryMetric)(nil),                    // 6: database_monitoring.v1.QueryMetric
}
var file_database_monitoring_v1_collector_metrics_proto_depIdxs = []int32{
	4, // 0: database_monitoring.v1.DatabaseMetrics.server:type_name -> database_monitoring.v1.ServerMetadata
	5, // 1: database_monitoring.v1.DatabaseMetrics.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: database_monitoring.v1.DatabaseMetrics.query_metrics:type_name -> database_monitoring.v1.DatabaseMetrics.QueryMetricSample
	1, // 3: database_monitoring.v1.DatabaseMetrics.system_metrics:type_name -> database_monitoring.v1.SystemMetrics
	2, // 4: database_monitoring.v1.SystemMetrics.counters:type_name -> database_monitoring.v1.PerformanceCounters
	6, // 5: database_monitoring.v1.DatabaseMetrics.QueryMetricSample.query_metrics:type_name -> database_monitoring.v1.QueryMetric
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_database_monitoring_v1_collector_metrics_proto_init() }
func file_database_monitoring_v1_collector_metrics_proto_init() {
	if File_database_monitoring_v1_collector_metrics_proto != nil {
		return
	}
	file_database_monitoring_v1_collector_metrics_proto_msgTypes[0].OneofWrappers = []any{
		(*DatabaseMetrics_QueryMetrics)(nil),
		(*DatabaseMetrics_SystemMetrics)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_monitoring_v1_collector_metrics_proto_rawDesc), len(file_database_monitoring_v1_collector_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_monitoring_v1_collector_metrics_proto_goTypes,
		DependencyIndexes: file_database_monitoring_v1_collector_metrics_proto_depIdxs,
		MessageInfos:      file_database_monitoring_v1_collector_metrics_proto_msgTypes,
	}.Build()
	File_database_monitoring_v1_collector_metrics_proto = out.File
	file_database_monitoring_v1_collector_metrics_proto_goTypes = nil
	file_database_monitoring_v1_collector_metrics_proto_depIdxs = nil
}
