// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.1
// source: database_monitoring/querier/v2/querier_api.proto

package querierv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuerierAPI_ListSnapshotSummaries_FullMethodName     = "/database_monitoring.v2.QuerierAPI/ListSnapshotSummaries"
	QuerierAPI_GetSnapshot_FullMethodName               = "/database_monitoring.v2.QuerierAPI/GetSnapshot"
	QuerierAPI_ListServerSummary_FullMethodName         = "/database_monitoring.v2.QuerierAPI/ListServerSummary"
	QuerierAPI_GetSampleDetails_FullMethodName          = "/database_monitoring.v2.QuerierAPI/GetSampleDetails"
	QuerierAPI_ListQueryMetrics_FullMethodName          = "/database_monitoring.v2.QuerierAPI/ListQueryMetrics"
	QuerierAPI_GetQueryMetricsTimeSeries_FullMethodName = "/database_monitoring.v2.QuerierAPI/GetQueryMetricsTimeSeries"
	QuerierAPI_ListPlansWithIssues_FullMethodName       = "/database_monitoring.v2.QuerierAPI/ListPlansWithIssues"
)

// QuerierAPIClient is the client API for QuerierAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuerierAPIClient interface {
	ListSnapshotSummaries(ctx context.Context, in *ListSnapshotSummariesRequest, opts ...grpc.CallOption) (*ListSnapshotSummariesResponse, error)
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	ListServerSummary(ctx context.Context, in *ListServerSummaryRequest, opts ...grpc.CallOption) (*ListServerSummaryResponse, error)
	GetSampleDetails(ctx context.Context, in *GetSampleDetailsRequest, opts ...grpc.CallOption) (*GetSampleDetailsResponse, error)
	ListQueryMetrics(ctx context.Context, in *ListQueryMetricsRequest, opts ...grpc.CallOption) (*ListQueryMetricsResponse, error)
	GetQueryMetricsTimeSeries(ctx context.Context, in *GetQueryMetricsTimeSeriesRequest, opts ...grpc.CallOption) (*GetQueryMetricsTimeSeriesResponse, error)
	ListPlansWithIssues(ctx context.Context, in *ListPlansWithIssuesRequest, opts ...grpc.CallOption) (*ListPlansWithIssuesResponse, error)
}

type querierAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewQuerierAPIClient(cc grpc.ClientConnInterface) QuerierAPIClient {
	return &querierAPIClient{cc}
}

func (c *querierAPIClient) ListSnapshotSummaries(ctx context.Context, in *ListSnapshotSummariesRequest, opts ...grpc.CallOption) (*ListSnapshotSummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotSummariesResponse)
	err := c.cc.Invoke(ctx, QuerierAPI_ListSnapshotSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierAPIClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, QuerierAPI_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierAPIClient) ListServerSummary(ctx context.Context, in *ListServerSummaryRequest, opts ...grpc.CallOption) (*ListServerSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServerSummaryResponse)
	err := c.cc.Invoke(ctx, QuerierAPI_ListServerSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierAPIClient) GetSampleDetails(ctx context.Context, in *GetSampleDetailsRequest, opts ...grpc.CallOption) (*GetSampleDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSampleDetailsResponse)
	err := c.cc.Invoke(ctx, QuerierAPI_GetSampleDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierAPIClient) ListQueryMetrics(ctx context.Context, in *ListQueryMetricsRequest, opts ...grpc.CallOption) (*ListQueryMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQueryMetricsResponse)
	err := c.cc.Invoke(ctx, QuerierAPI_ListQueryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierAPIClient) GetQueryMetricsTimeSeries(ctx context.Context, in *GetQueryMetricsTimeSeriesRequest, opts ...grpc.CallOption) (*GetQueryMetricsTimeSeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueryMetricsTimeSeriesResponse)
	err := c.cc.Invoke(ctx, QuerierAPI_GetQueryMetricsTimeSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierAPIClient) ListPlansWithIssues(ctx context.Context, in *ListPlansWithIssuesRequest, opts ...grpc.CallOption) (*ListPlansWithIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlansWithIssuesResponse)
	err := c.cc.Invoke(ctx, QuerierAPI_ListPlansWithIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuerierAPIServer is the server API for QuerierAPI service.
// All implementations must embed UnimplementedQuerierAPIServer
// for forward compatibility.
type QuerierAPIServer interface {
	ListSnapshotSummaries(context.Context, *ListSnapshotSummariesRequest) (*ListSnapshotSummariesResponse, error)
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	ListServerSummary(context.Context, *ListServerSummaryRequest) (*ListServerSummaryResponse, error)
	GetSampleDetails(context.Context, *GetSampleDetailsRequest) (*GetSampleDetailsResponse, error)
	ListQueryMetrics(context.Context, *ListQueryMetricsRequest) (*ListQueryMetricsResponse, error)
	GetQueryMetricsTimeSeries(context.Context, *GetQueryMetricsTimeSeriesRequest) (*GetQueryMetricsTimeSeriesResponse, error)
	ListPlansWithIssues(context.Context, *ListPlansWithIssuesRequest) (*ListPlansWithIssuesResponse, error)
	mustEmbedUnimplementedQuerierAPIServer()
}

// UnimplementedQuerierAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuerierAPIServer struct{}

func (UnimplementedQuerierAPIServer) ListSnapshotSummaries(context.Context, *ListSnapshotSummariesRequest) (*ListSnapshotSummariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshotSummaries not implemented")
}
func (UnimplementedQuerierAPIServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedQuerierAPIServer) ListServerSummary(context.Context, *ListServerSummaryRequest) (*ListServerSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServerSummary not implemented")
}
func (UnimplementedQuerierAPIServer) GetSampleDetails(context.Context, *GetSampleDetailsRequest) (*GetSampleDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSampleDetails not implemented")
}
func (UnimplementedQuerierAPIServer) ListQueryMetrics(context.Context, *ListQueryMetricsRequest) (*ListQueryMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueryMetrics not implemented")
}
func (UnimplementedQuerierAPIServer) GetQueryMetricsTimeSeries(context.Context, *GetQueryMetricsTimeSeriesRequest) (*GetQueryMetricsTimeSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueryMetricsTimeSeries not implemented")
}
func (UnimplementedQuerierAPIServer) ListPlansWithIssues(context.Context, *ListPlansWithIssuesRequest) (*ListPlansWithIssuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlansWithIssues not implemented")
}
func (UnimplementedQuerierAPIServer) mustEmbedUnimplementedQuerierAPIServer() {}
func (UnimplementedQuerierAPIServer) testEmbeddedByValue()                    {}

// UnsafeQuerierAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuerierAPIServer will
// result in compilation errors.
type UnsafeQuerierAPIServer interface {
	mustEmbedUnimplementedQuerierAPIServer()
}

func RegisterQuerierAPIServer(s grpc.ServiceRegistrar, srv QuerierAPIServer) {
	// If the following call pancis, it indicates UnimplementedQuerierAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuerierAPI_ServiceDesc, srv)
}

func _QuerierAPI_ListSnapshotSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierAPIServer).ListSnapshotSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuerierAPI_ListSnapshotSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierAPIServer).ListSnapshotSummaries(ctx, req.(*ListSnapshotSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuerierAPI_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierAPIServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuerierAPI_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierAPIServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuerierAPI_ListServerSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServerSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierAPIServer).ListServerSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuerierAPI_ListServerSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierAPIServer).ListServerSummary(ctx, req.(*ListServerSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuerierAPI_GetSampleDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSampleDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierAPIServer).GetSampleDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuerierAPI_GetSampleDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierAPIServer).GetSampleDetails(ctx, req.(*GetSampleDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuerierAPI_ListQueryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierAPIServer).ListQueryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuerierAPI_ListQueryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierAPIServer).ListQueryMetrics(ctx, req.(*ListQueryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuerierAPI_GetQueryMetricsTimeSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueryMetricsTimeSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierAPIServer).GetQueryMetricsTimeSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuerierAPI_GetQueryMetricsTimeSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierAPIServer).GetQueryMetricsTimeSeries(ctx, req.(*GetQueryMetricsTimeSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuerierAPI_ListPlansWithIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlansWithIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierAPIServer).ListPlansWithIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuerierAPI_ListPlansWithIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierAPIServer).ListPlansWithIssues(ctx, req.(*ListPlansWithIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuerierAPI_ServiceDesc is the grpc.ServiceDesc for QuerierAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuerierAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "database_monitoring.v2.QuerierAPI",
	HandlerType: (*QuerierAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSnapshotSummaries",
			Handler:    _QuerierAPI_ListSnapshotSummaries_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _QuerierAPI_GetSnapshot_Handler,
		},
		{
			MethodName: "ListServerSummary",
			Handler:    _QuerierAPI_ListServerSummary_Handler,
		},
		{
			MethodName: "GetSampleDetails",
			Handler:    _QuerierAPI_GetSampleDetails_Handler,
		},
		{
			MethodName: "ListQueryMetrics",
			Handler:    _QuerierAPI_ListQueryMetrics_Handler,
		},
		{
			MethodName: "GetQueryMetricsTimeSeries",
			Handler:    _QuerierAPI_GetQueryMetricsTimeSeries_Handler,
		},
		{
			MethodName: "ListPlansWithIssues",
			Handler:    _QuerierAPI_ListPlansWithIssues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database_monitoring/querier/v2/querier_api.proto",
}
